/**
 * Knoux Clipboard AI - Main Application Component
 * Root component for the entire application UI
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import React, { useEffect, useState, useCallback } from 'react';
import { Routes, Route, Navigate, useLocation } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import styled, { ThemeProvider } from 'styled-components';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// Components
import { Sidebar } from './components/Sidebar';
import { TopBar } from './components/TopBar';
import { StatusBar } from './components/StatusBar';
import { QuickSearch } from './components/QuickSearch';
import { NotificationCenter } from './components/NotificationCenter';
import { CommandPalette } from './components/CommandPalette';
import { LoadingOverlay } from './components/LoadingOverlay';
import { ErrorBoundary } from './components/ErrorBoundary';

// Views
import { Dashboard } from './views/Dashboard';
import { ClipboardHistory } from './views/ClipboardHistory';
import { AIInsights } from './views/AIInsights';
import { SecurityCenter } from './views/SecurityCenter';
import { SettingsPanel } from './views/SettingsPanel';
import { About } from './views/About';

// Hooks
import { useClipboard } from './hooks/useClipboard';
import { useAI } from './hooks/useAI';
import { useHotkeys } from './hooks/useHotkeys';
import { useAppEvents } from './hooks/useAppEvents';
import { useSettings } from './hooks/useSettings';

// Store
import { 
  selectAppState, 
  selectSettings, 
  selectNotifications,
  selectIsLoading,
  selectError,
  initializeApp,
  setTheme,
  addNotification,
  clearError
} from './store';

// Services
import { theme } from './styles/theme';
import { logger } from './shared/logger';

// Styles
import './styles/global.css';
import './styles/animations.css';

// ==================== STYLED COMPONENTS ====================

const AppContainer = styled.div<{ sidebarCollapsed: boolean }>`
  display: flex;
  flex-direction: column;
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  background: ${props => props.theme.colors.background.primary};
  color: ${props => props.theme.colors.text.primary};
  transition: background-color 0.3s ease, color 0.3s ease;
`;

const MainContent = styled.div<{ sidebarCollapsed: boolean }>`
  display: flex;
  flex: 1;
  overflow: hidden;
  position: relative;
`;

const SidebarContainer = styled.div<{ collapsed: boolean }>`
  width: ${props => props.collapsed ? '60px' : '250px'};
  min-width: ${props => props.collapsed ? '60px' : '250px'};
  height: 100%;
  background: ${props => props.theme.colors.background.secondary};
  border-right: 1px solid ${props => props.theme.colors.border};
  transition: width 0.3s ease, min-width 0.3s ease;
  overflow: hidden;
  z-index: 100;
`;

const ContentArea = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
`;

const ViewContainer = styled.div`
  flex: 1;
  overflow: hidden;
  position: relative;
  padding: 0;
`;

const LoadingContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: ${props => props.theme.colors.background.primary};
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  opacity: 0.95;
`;

const ErrorContainer = styled.div`
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: ${props => props.theme.colors.background.primary};
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 2rem;
`;

const ErrorContent = styled.div`
  max-width: 500px;
  text-align: center;
  background: ${props => props.theme.colors.background.secondary};
  border-radius: 12px;
  padding: 2rem;
  border: 1px solid ${props => props.theme.colors.border};
  box-shadow: ${props => props.theme.shadows.large};
`;

const ErrorTitle = styled.h2`
  color: ${props => props.theme.colors.error};
  margin-bottom: 1rem;
  font-size: 1.5rem;
`;

const ErrorMessage = styled.p`
  color: ${props => props.theme.colors.text.secondary};
  margin-bottom: 1.5rem;
  line-height: 1.5;
`;

const ErrorAction = styled.button`
  background: ${props => props.theme.colors.primary};
  color: white;
  border: none;
  border-radius: 8px;
  padding: 0.75rem 1.5rem;
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  
  &:hover {
    background: ${props => props.theme.colors.primaryDark};
    transform: translateY(-2px);
  }
  
  &:active {
    transform: translateY(0);
  }
`;

// ==================== MAIN APP COMPONENT ====================

const App: React.FC = () => {
  const dispatch = useDispatch();
  const location = useLocation();
  
  // State from Redux store
  const appState = useSelector(selectAppState);
  const settings = useSelector(selectSettings);
  const notifications = useSelector(selectNotifications);
  const isLoading = useSelector(selectIsLoading);
  const appError = useSelector(selectError);
  
  // Local state
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [showQuickSearch, setShowQuickSearch] = useState(false);
  const [showCommandPalette, setShowCommandPalette] = useState(false);
  const [showNotificationCenter, setShowNotificationCenter] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);
  
  // Custom hooks
  const clipboard = useClipboard();
  const ai = useAI();
  const hotkeys = useHotkeys();
  const appEvents = useAppEvents();
  const settingsHook = useSettings();
  
  // ==================== EFFECTS ====================
  
  // Initialize application
  useEffect(() => {
    const initApp = async () => {
      try {
        logger.info('Initializing application component');
        
        // Initialize Redux store
        await dispatch(initializeApp() as any);
        
        // Apply theme from settings
        if (settings.ui?.theme) {
          dispatch(setTheme(settings.ui.theme));
        }
        
        // Start clipboard monitoring
        await clipboard.startMonitoring();
        
        // Initialize AI engine if enabled
        if (settings.ai?.enabled) {
          await ai.initialize();
        }
        
        // Setup hotkeys
        hotkeys.setup();
        
        // Listen to app events
        appEvents.setup();
        
        setIsInitialized(true);
        logger.info('Application component initialized successfully');
        
        // Show welcome notification
        dispatch(addNotification({
          id: 'welcome',
          type: 'info',
          title: 'Welcome to Knoux Clipboard AI',
          message: 'Your clipboard is now intelligent! Start copying and see the magic.',
          duration: 5000,
        }));
        
      } catch (error) {
        logger.error('Failed to initialize application component', error as Error);
        toast.error('Failed to initialize application');
      }
    };
    
    if (!isInitialized) {
      initApp();
    }
  }, [dispatch, isInitialized, settings, clipboard, ai, hotkeys, appEvents]);
  
  // Handle theme changes
  useEffect(() => {
    if (settings.ui?.theme) {
      dispatch(setTheme(settings.ui.theme));
    }
  }, [settings.ui?.theme, dispatch]);
  
  // Handle app errors
  useEffect(() => {
    if (appError) {
      logger.error('Application error detected', new Error(appError.message));
      toast.error(appError.message);
      
      // Auto-clear error after 5 seconds
      const timer = setTimeout(() => {
        dispatch(clearError());
      }, 5000);
      
      return () => clearTimeout(timer);
    }
  }, [appError, dispatch]);
  
  // Handle notifications
  useEffect(() => {
    notifications.forEach(notification => {
      if (!notification.read) {
        toast[notification.type || 'info'](notification.message, {
          toastId: notification.id,
          autoClose: notification.duration || 5000,
          onClose: () => {
            // Mark as read when toast closes
          },
        });
      }
    });
  }, [notifications]);
  
  // ==================== EVENT HANDLERS ====================
  
  const handleSidebarToggle = useCallback(() => {
    setSidebarCollapsed(!sidebarCollapsed);
  }, [sidebarCollapsed]);
  
  const handleQuickSearchToggle = useCallback(() => {
    setShowQuickSearch(!showQuickSearch);
  }, [showQuickSearch]);
  
  const handleCommandPaletteToggle = useCallback(() => {
    setShowCommandPalette(!showCommandPalette);
  }, [showCommandPalette]);
  
  const handleNotificationCenterToggle = useCallback(() => {
    setShowNotificationCenter(!showNotificationCenter);
  }, [showNotificationCenter]);
  
  const handleRetry = useCallback(() => {
    dispatch(clearError());
    setIsInitialized(false);
  }, [dispatch]);
  
  const handleClipboardClear = useCallback(async () => {
    try {
      await clipboard.clearHistory();
      toast.success('Clipboard history cleared');
    } catch (error) {
      logger.error('Failed to clear clipboard history', error as Error);
      toast.error('Failed to clear clipboard history');
    }
  }, [clipboard]);
  
  const handleAIAnalyze = useCallback(async (content: string) => {
    try {
      const analysis = await ai.analyze(content);
      return analysis;
    } catch (error) {
      logger.error('AI analysis failed', error as Error);
      toast.error('AI analysis failed');
      return null;
    }
  }, [ai]);
  
  const handleSettingsSave = useCallback(async (updates: any) => {
    try {
      await settingsHook.update(updates);
      toast.success('Settings saved');
    } catch (error) {
      logger.error('Failed to save settings', error as Error);
      toast.error('Failed to save settings');
    }
  }, [settingsHook]);
  
  // ==================== HOTKEY HANDLERS ====================
  
  // Setup global hotkeys
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Ctrl/Cmd + K for quick search
      if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
        event.preventDefault();
        handleQuickSearchToggle();
      }
      
      // Ctrl/Cmd + Shift + P for command palette
      if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key === 'P') {
        event.preventDefault();
        handleCommandPaletteToggle();
      }
      
      // Ctrl/Cmd + Shift + N for notifications
      if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key === 'N') {
        event.preventDefault();
        handleNotificationCenterToggle();
      }
      
      // Esc to close modals
      if (event.key === 'Escape') {
        if (showQuickSearch) setShowQuickSearch(false);
        if (showCommandPalette) setShowCommandPalette(false);
        if (showNotificationCenter) setShowNotificationCenter(false);
      }
    };
    
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [showQuickSearch, showCommandPalette, showNotificationCenter, handleQuickSearchToggle, handleCommandPaletteToggle, handleNotificationCenterToggle]);
  
  // ==================== RENDER LOGIC ====================
  
  // Show loading screen during initialization
  if (!isInitialized || isLoading) {
    return (
      <ThemeProvider theme={theme}>
        <LoadingContainer>
          <LoadingOverlay 
            message="Initializing Knoux Clipboard AI..."
            progress={isInitialized ? 0.7 : 0.3}
          />
        </LoadingContainer>
      </ThemeProvider>
    );
  }
  
  // Show error screen if there's a critical error
  if (appError?.critical) {
    return (
      <ThemeProvider theme={theme}>
        <ErrorContainer>
          <ErrorContent>
            <ErrorTitle>Application Error</ErrorTitle>
            <ErrorMessage>
              {appError.message || 'An unexpected error occurred. Please try restarting the application.'}
            </ErrorMessage>
            <ErrorAction onClick={handleRetry}>
              Retry
            </ErrorAction>
          </ErrorContent>
        </ErrorContainer>
      </ThemeProvider>
    );
  }
  
  // Main application render
  return (
    <ThemeProvider theme={theme}>
      <ErrorBoundary>
        <AppContainer sidebarCollapsed={sidebarCollapsed}>
          {/* Top Navigation Bar */}
          <TopBar
            onSidebarToggle={handleSidebarToggle}
            onQuickSearchToggle={handleQuickSearchToggle}
            onCommandPaletteToggle={handleCommandPaletteToggle}
            onNotificationToggle={handleNotificationCenterToggle}
            sidebarCollapsed={sidebarCollapsed}
            clipboardStats={clipboard.stats}
            aiStatus={ai.status}
          />
          
          <MainContent sidebarCollapsed={sidebarCollapsed}>
            {/* Sidebar */}
            <SidebarContainer collapsed={sidebarCollapsed}>
              <Sidebar
                collapsed={sidebarCollapsed}
                currentPath={location.pathname}
                onToggle={handleSidebarToggle}
                clipboardStats={clipboard.stats}
                securityAlerts={appState.securityAlerts}
              />
            </SidebarContainer>
            
            {/* Main Content Area */}
            <ContentArea>
              <ViewContainer>
                <Routes>
                  <Route path="/" element={<Navigate to="/dashboard" replace />} />
                  <Route path="/dashboard" element={
                    <Dashboard
                      clipboard={clipboard}
                      ai={ai}
                      settings={settings}
                    />
                  } />
                  <Route path="/clipboard" element={
                    <ClipboardHistory
                      items={clipboard.items}
                      onItemSelect={clipboard.selectItem}
                      onItemDelete={clipboard.deleteItem}
                      onItemFavorite={clipboard.favoriteItem}
                      onClearAll={handleClipboardClear}
                      isLoading={clipboard.isLoading}
                    />
                  } />
                  <Route path="/ai" element={
                    <AIInsights
                      analyses={ai.analyses}
                      onAnalyze={handleAIAnalyze}
                      suggestions={ai.suggestions}
                      isLoading={ai.isLoading}
                    />
                  } />
                  <Route path="/security" element={
                    <SecurityCenter
                      alerts={appState.securityAlerts}
                      scans={appState.securityScans}
                      settings={settings.security}
                    />
                  } />
                  <Route path="/settings" element={
                    <SettingsPanel
                      settings={settings}
                      onSave={handleSettingsSave}
                      onReset={() => settingsHook.reset()}
                    />
                  } />
                  <Route path="/about" element={
                    <About
                      version={appState.version}
                      stats={appState.stats}
                    />
                  } />
                  <Route path="*" element={<Navigate to="/dashboard" replace />} />
                </Routes>
              </ViewContainer>
            </ContentArea>
          </MainContent>
          
          {/* Status Bar */}
          <StatusBar
            clipboardCount={clipboard.stats.total}
            aiEnabled={settings.ai?.enabled}
            securityStatus={appState.securityStatus}
            memoryUsage={appState.memoryUsage}
          />
          
          {/* Modal Overlays */}
          {showQuickSearch && (
            <QuickSearch
              onClose={() => setShowQuickSearch(false)}
              onSearch={(query) => {
                console.log('Search:', query);
                setShowQuickSearch(false);
              }}
              recentSearches={clipboard.recentSearches}
            />
          )}
          
          {showCommandPalette && (
            <CommandPalette
              onClose={() => setShowCommandPalette(false)}
              onCommand={(command) => {
                console.log('Command:', command);
                setShowCommandPalette(false);
              }}
              commands={appState.commands}
            />
          )}
          
          {showNotificationCenter && (
            <NotificationCenter
              onClose={() => setShowNotificationCenter(false)}
              notifications={notifications}
              onClearAll={() => {
                // Clear all notifications
              }}
            />
          )}
          
          {/* Toast Notifications */}
          <ToastContainer
            position="bottom-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme={settings.ui?.theme === 'dark' ? 'dark' : 'light'}
            style={{ zIndex: 9999 }}
          />
        </AppContainer>
      </ErrorBoundary>
    </ThemeProvider>
  );
};

// ==================== EXPORT ====================

export default App;

// Performance optimization
export const MemoizedApp = React.memo(App);
