// Generated by Knoux-Integrator AI — 2026-01-26 — Updated to use window.knoux API
/**
 * Clipboard Management Hook
 * Provides clipboard operations with caching, polling, and real-time updates
 */

import { useState, useCallback, useEffect, useRef } from "react";

interface UseClipboardReturn {
  items: any[];
  isLoading: boolean;
  error: string | null;
  refresh: () => Promise<void>;
  copyToClipboard: (content: string) => Promise<boolean>;
  clearAll: () => Promise<boolean>;
}

export const useClipboard = (): UseClipboardReturn => {
  const [items, setItems] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Fetch clipboard history using window.knoux API
  const refresh = useCallback(async () => {
    if (!window.knoux?.clipboard?.read) {
      setError('Clipboard API not available');
      return;
    }

    try {
      setIsLoading(true);
      setError(null);
      
      const response = await window.knoux.clipboard.read();
      
      if (response && response.ok) {
        setItems(response.data || []);
      } else {
        setError(response?.error || 'Failed to load clipboard');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Copy to clipboard using window.knoux API
  const copyToClipboard = useCallback(async (content: string): Promise<boolean> => {
    if (!window.knoux?.clipboard?.write) {
      setError('Clipboard write API not available');
      return false;
    }

    try {
      const response = await window.knoux.clipboard.write({ content, timestamp: Date.now() });
      
      if (response && response.ok) {
        await refresh(); // Refresh to show new item
        return true;
      } else {
        setError(response?.error || 'Failed to copy');
        return false;
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Copy failed');
      return false;
    }
  }, [refresh]);

  // Clear all clipboard items
  const clearAll = useCallback(async (): Promise<boolean> => {
    if (!window.knoux?.clipboard?.history) {
      setError('Clipboard clear API not available');
      return false;
    }

    try {
      // TODO: Add clear API to IPC handlers
      setItems([]);
      return true;
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Clear failed');
      return false;
    }
  }, []);

  // Auto-refresh on mount
  useEffect(() => {
    refresh();
    
    // Poll every 3 seconds
    const interval = setInterval(refresh, 3000);
    
    return () => clearInterval(interval);
  }, [refresh]);

  return {
    items,
    isLoading,
    error,
    refresh,
    copyToClipboard,
    clearAll
  };
};

// Global type declaration for window.knoux
declare global {
  interface Window {
    knoux?: {
      clipboard: {
        read: () => Promise<{ ok: boolean; data?: any[]; error?: string }>;
        write: (item: any) => Promise<{ ok: boolean; error?: string }>;
        history: () => Promise<{ ok: boolean; data?: any[]; error?: string }>;
        normalize: (content: string) => Promise<{ ok: boolean; data?: any; error?: string }>;
        format: (content: string, format: string) => Promise<{ ok: boolean; data?: any; error?: string }>;
      };
      ai: {
        summarize: (text: string) => Promise<{ ok: boolean; data?: string; error?: string }>;
        enhance: (text: string, opts?: any) => Promise<{ ok: boolean; data?: string; error?: string }>;
        predict: (context: any) => Promise<{ ok: boolean; data?: any; error?: string }>;
      };
      storage: {
        get: (key: string) => Promise<{ ok: boolean; data?: any; error?: string }>;
        set: (key: string, value: any) => Promise<{ ok: boolean; error?: string }>;
        export: () => Promise<{ ok: boolean; data?: any; error?: string }>;
      };
    };
  }
}

export default useClipboard;
