// Enhanced AI IPC with Real Processing Capabilities
// Generated by Knoux-Integrator AI — 2026-01-26

const { ipcMain } = require('electron');

// Enhanced AI service with better mock capabilities
const enhancedAIService = {
  // Text summarization with intelligent processing
  async summarize(text) {
    if (!text || typeof text !== 'string') {
      throw new Error('Invalid text input for summarization');
    }
    
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 10);
    
    if (sentences.length <= 2) {
      return {
        summary: text.trim(),
        originalLength: text.length,
        summaryLength: text.trim().length,
        compressionRatio: 1.0,
        keyPoints: [text.trim()]
      };
    }
    
    // Simple extractive summarization
    const keyWords = this.extractKeywords(text);
    const scoredSentences = sentences.map(sentence => ({
      text: sentence.trim(),
      score: this.scoreSentence(sentence, keyWords)
    }));
    
    // Sort by score and take top sentences
    const topSentences = scoredSentences
      .sort((a, b) => b.score - a.score)
      .slice(0, Math.max(1, Math.ceil(sentences.length * 0.3)))
      .map(s => s.text);
    
    const summary = topSentences.join('. ') + '.';
    
    return {
      summary,
      originalLength: text.length,
      summaryLength: summary.length,
      compressionRatio: summary.length / text.length,
      keyPoints: topSentences,
      keywords: keyWords.slice(0, 5)
    };
  },
  
  // Text enhancement with multiple improvement types
  async enhance(text, options = {}) {
    if (!text || typeof text !== 'string') {
      throw new Error('Invalid text input for enhancement');
    }
    
    const {
      tone = 'professional',
      style = 'clear',
      fixGrammar = true,
      improveClarity = true
    } = options;
    
    let enhanced = text;
    const improvements = [];
    
    // Basic grammar fixes
    if (fixGrammar) {
      enhanced = this.fixBasicGrammar(enhanced);
      improvements.push('Grammar corrections applied');
    }
    
    // Tone adjustment
    if (tone === 'professional') {
      enhanced = this.makeProfessional(enhanced);
      improvements.push('Professional tone applied');
    } else if (tone === 'casual') {
      enhanced = this.makeCasual(enhanced);
      improvements.push('Casual tone applied');
    }
    
    // Clarity improvements
    if (improveClarity) {
      enhanced = this.improveClarity(enhanced);
      improvements.push('Clarity improvements applied');
    }
    
    return {
      original: text,
      enhanced,
      improvements,
      confidence: 0.85,
      changes: this.detectChanges(text, enhanced)
    };
  },
  
  // Predictive analysis
  async predict(context) {
    if (!context) {
      return {
        prediction: 'No context provided',
        confidence: 0.0,
        suggestions: []
      };
    }
    
    const predictions = [];
    
    // Analyze clipboard patterns
    if (context.clipboardHistory) {
      const recentTypes = context.clipboardHistory.slice(0, 5).map(item => item.type);
      const mostCommon = this.getMostCommon(recentTypes);
      predictions.push({
        type: 'content_type',
        prediction: `Next clipboard item likely to be: ${mostCommon}`,
        confidence: 0.7
      });
    }
    
    // Time-based predictions
    const hour = new Date().getHours();
    if (hour >= 9 && hour <= 17) {
      predictions.push({
        type: 'usage_pattern',
        prediction: 'Work-related content expected during business hours',
        confidence: 0.6
      });
    }
    
    // Content analysis
    if (context.currentContent) {
      const contentType = this.analyzeContentType(context.currentContent);
      predictions.push({
        type: 'content_analysis',
        prediction: `Content appears to be ${contentType}`,
        confidence: 0.8
      });
    }
    
    return {
      predictions,
      overallConfidence: predictions.length > 0 ? 
        predictions.reduce((sum, p) => sum + p.confidence, 0) / predictions.length : 0,
      suggestions: this.generateSuggestions(context)
    };
  },
  
  // Content classification
  async classify(content) {
    const type = this.analyzeContentType(content);
    const language = this.detectLanguage(content);
    const sentiment = this.analyzeSentiment(content);
    
    return {
      type,
      language,
      sentiment,
      confidence: 0.75,
      metadata: {
        wordCount: content.split(/\s+/).length,
        charCount: content.length,
        hasUrls: /https?:\/\//.test(content),
        hasEmails: /@[^\s]+\.[^\s]+/.test(content)
      }
    };
  },
  
  // Helper methods
  extractKeywords(text) {
    const words = text.toLowerCase()
      .replace(/[^\w\s]/g, '')
      .split(/\s+/)
      .filter(word => word.length > 3);
    
    const frequency = {};
    words.forEach(word => {
      frequency[word] = (frequency[word] || 0) + 1;
    });
    
    return Object.entries(frequency)
      .sort(([,a], [,b]) => b - a)
      .slice(0, 10)
      .map(([word]) => word);
  },
  
  scoreSentence(sentence, keywords) {
    const words = sentence.toLowerCase().split(/\s+/);
    let score = 0;
    
    keywords.forEach(keyword => {
      if (words.includes(keyword)) {
        score += 1;
      }
    });
    
    // Bonus for sentence length (not too short, not too long)
    if (words.length >= 5 && words.length <= 20) {
      score += 0.5;
    }
    
    return score;
  },
  
  fixBasicGrammar(text) {
    return text
      .replace(/\bi\b/g, 'I')
      .replace(/\s+/g, ' ')
      .replace(/([.!?])\s*([a-z])/g, (match, punct, letter) => punct + ' ' + letter.toUpperCase())
      .trim();
  },
  
  makeProfessional(text) {
    return text
      .replace(/\bcan't\b/g, 'cannot')
      .replace(/\bwon't\b/g, 'will not')
      .replace(/\bdon't\b/g, 'do not')
      .replace(/\bisn't\b/g, 'is not');
  },
  
  makeCasual(text) {
    return text
      .replace(/\bcannot\b/g, "can't")
      .replace(/\bwill not\b/g, "won't")
      .replace(/\bdo not\b/g, "don't")
      .replace(/\bis not\b/g, "isn't");
  },
  
  improveClarity(text) {
    return text
      .replace(/\bthat that\b/g, 'that')
      .replace(/\bvery very\b/g, 'extremely')
      .replace(/\s{2,}/g, ' ')
      .trim();
  },
  
  detectChanges(original, enhanced) {
    const changes = [];
    if (original.length !== enhanced.length) {
      changes.push(`Length changed from ${original.length} to ${enhanced.length} characters`);
    }
    if (original !== enhanced) {
      changes.push('Content modified');
    }
    return changes;
  },
  
  getMostCommon(array) {
    const frequency = {};
    array.forEach(item => {
      frequency[item] = (frequency[item] || 0) + 1;
    });
    
    return Object.entries(frequency)
      .sort(([,a], [,b]) => b - a)[0]?.[0] || 'text';
  },
  
  analyzeContentType(content) {
    if (/^https?:\/\/.+/.test(content.trim())) return 'url';
    if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(content.trim())) return 'email';
    if (/^\d+(\.\d+)?$/.test(content.trim())) return 'number';
    if (/^(function|class|const|let|var|if|for|while)\s/.test(content)) return 'code';
    if (content.includes('\n') && content.split('\n').length > 3) return 'document';
    return 'text';
  },
  
  detectLanguage(content) {
    // Simple language detection
    if (/[\u0600-\u06FF]/.test(content)) return 'arabic';
    if (/[\u4e00-\u9fff]/.test(content)) return 'chinese';
    if (/[\u3040-\u309f\u30a0-\u30ff]/.test(content)) return 'japanese';
    return 'english';
  },
  
  analyzeSentiment(content) {
    const positiveWords = ['good', 'great', 'excellent', 'amazing', 'wonderful', 'fantastic'];
    const negativeWords = ['bad', 'terrible', 'awful', 'horrible', 'disappointing', 'poor'];
    
    const words = content.toLowerCase().split(/\s+/);
    let score = 0;
    
    words.forEach(word => {
      if (positiveWords.includes(word)) score += 1;
      if (negativeWords.includes(word)) score -= 1;
    });
    
    if (score > 0) return 'positive';
    if (score < 0) return 'negative';
    return 'neutral';
  },
  
  generateSuggestions(context) {
    const suggestions = [];
    
    if (context.currentContent) {
      const type = this.analyzeContentType(context.currentContent);
      
      if (type === 'url') {
        suggestions.push('Consider bookmarking this URL');
        suggestions.push('Check if this link is safe before sharing');
      } else if (type === 'code') {
        suggestions.push('Format this code for better readability');
        suggestions.push('Add comments to explain the code');
      } else if (type === 'text') {
        suggestions.push('Check spelling and grammar');
        suggestions.push('Consider shortening for clarity');
      }
    }
    
    return suggestions;
  }
};

function registerAIIPC() {
  console.log('🧠 Registering Enhanced AI IPC handlers...');

  // Text summarization
  ipcMain.handle('knoux.ai.summarize', async (evt, text) => {
    try {
      const result = await enhancedAIService.summarize(text);
      return { ok: true, data: result };
    } catch (error) {
      console.error('❌ AI summarize error:', error);
      return { ok: false, error: error.message };
    }
  });

  // Text enhancement
  ipcMain.handle('knoux.ai.enhance', async (evt, text, options) => {
    try {
      const result = await enhancedAIService.enhance(text, options);
      return { ok: true, data: result };
    } catch (error) {
      console.error('❌ AI enhance error:', error);
      return { ok: false, error: error.message };
    }
  });

  // Predictive analysis
  ipcMain.handle('knoux.ai.predict', async (evt, context) => {
    try {
      const result = await enhancedAIService.predict(context);
      return { ok: true, data: result };
    } catch (error) {
      console.error('❌ AI predict error:', error);
      return { ok: false, error: error.message };
    }
  });

  // Content classification
  ipcMain.handle('knoux.ai.classify', async (evt, content) => {
    try {
      const result = await enhancedAIService.classify(content);
      return { ok: true, data: result };
    } catch (error) {
      console.error('❌ AI classify error:', error);
      return { ok: false, error: error.message };
    }
  });

  // Batch processing
  ipcMain.handle('knoux.ai.batch', async (evt, { operation, items, options }) => {
    try {
      const results = [];
      
      for (const item of items) {
        let result;
        switch (operation) {
          case 'summarize':
            result = await enhancedAIService.summarize(item);
            break;
          case 'enhance':
            result = await enhancedAIService.enhance(item, options);
            break;
          case 'classify':
            result = await enhancedAIService.classify(item);
            break;
          default:
            throw new Error(`Unknown operation: ${operation}`);
        }
        results.push(result);
      }
      
      return { ok: true, data: results };
    } catch (error) {
      console.error('❌ AI batch error:', error);
      return { ok: false, error: error.message };
    }
  });

  console.log('✅ Enhanced AI IPC handlers registered');
}

module.exports = { registerAIIPC, enhancedAIService };
