export const AI = {
    ANALYSIS_TIMEOUT_MS: 30000,
    CACHE_DURATION_MINUTES: 60
};

export const ERROR_CODES = {
    AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
    TIMEOUT: 'TIMEOUT',
    INVALID_INPUT: 'INVALID_INPUT'
};
