/**
 * Knoux Clipboard AI - Enumerations
 * All enum values used throughout the application
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

// ==================== CLIPBOARD ENUMS ====================

/**
 * Clipboard content format types
 */
export enum ClipboardFormat {
  TEXT = 'text',
  HTML = 'html',
  RTF = 'rtf',
  IMAGE = 'image',
  FILES = 'files',
  CUSTOM = 'custom',
}

/**
 * Clipboard monitoring state
 */
export enum ClipboardState {
  ACTIVE = 'active',
  PAUSED = 'paused',
  DISABLED = 'disabled',
  ERROR = 'error',
}

/**
 * Clipboard item storage status
 */
export enum StorageStatus {
  PERSISTENT = 'persistent',
  TEMPORARY = 'temporary',
  ENCRYPTED = 'encrypted',
  ARCHIVED = 'archived',
  DELETED = 'deleted',
}

/**
 * Clipboard change detection mode
 */
export enum DetectionMode {
  POLLING = 'polling',
  EVENT_DRIVEN = 'event_driven',
  HYBRID = 'hybrid',
  MANUAL = 'manual',
}

// ==================== AI ENUMS ====================

/**
 * AI model types available
 */
export enum AIModelType {
  LOCAL_LLAMA = 'local_llama',
  LOCAL_GPT2 = 'local_gpt2',
  CLOUD_OPENAI = 'cloud_openai',
  CLOUD_ANTHROPIC = 'cloud_anthropic',
  CLOUD_GEMINI = 'cloud_gemini',
  CUSTOM_MODEL = 'custom_model',
}

/**
 * AI analysis status
 */
export enum AIAnalysisStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CACHED = 'cached',
  SKIPPED = 'skipped',
}

/**
 * AI task priority levels
 */
export enum AITaskPriority {
  REALTIME = 0,
  HIGH = 1,
  NORMAL = 2,
  LOW = 3,
  BACKGROUND = 4,
}

/**
 * AI suggestion categories
 */
export enum SuggestionCategory {
  CODE_QUALITY = 'code_quality',
  SECURITY = 'security',
  PERFORMANCE = 'performance',
  READABILITY = 'readability',
  BEST_PRACTICES = 'best_practices',
  OPTIMIZATION = 'optimization',
  DEBUGGING = 'debugging',
  FORMATTING = 'formatting',
  REFACTORING = 'refactoring',
  DOCUMENTATION = 'documentation',
}

// ==================== SECURITY ENUMS ====================

/**
 * Encryption algorithms supported
 */
export enum EncryptionAlgorithm {
  AES_GCM = 'AES-GCM',
  AES_CBC = 'AES-CBC',
  CHACHA20_POLY1305 = 'ChaCha20-Poly1305',
  RSA_OAEP = 'RSA-OAEP',
  RSA_PSS = 'RSA-PSS',
}

/**
 * Key derivation functions
 */
export enum KeyDerivationFunction {
  PBKDF2 = 'PBKDF2',
  SCRYPT = 'scrypt',
  ARGON2ID = 'argon2id',
  BCRYPT = 'bcrypt',
}

/**
 * Security alert levels
 */
export enum SecurityAlertLevel {
  CRITICAL = 4,
  HIGH = 3,
  MEDIUM = 2,
  LOW = 1,
  INFO = 0,
}

/**
 * Permission types for security
 */
export enum PermissionType {
  CLIPBOARD_READ = 'clipboard_read',
  CLIPBOARD_WRITE = 'clipboard_write',
  AI_ANALYSIS = 'ai_analysis',
  FILE_ACCESS = 'file_access',
  NETWORK_ACCESS = 'network_access',
  SYSTEM_INFO = 'system_info',
  AUTOSTART = 'autostart',
  NOTIFICATIONS = 'notifications',
}

// ==================== CONTENT ENUMS ====================

/**
 * Primary content categories
 */
export enum ContentCategory {
  CODE = 'code',
  TEXT = 'text',
  DATA = 'data',
  MEDIA = 'media',
  DOCUMENT = 'document',
  EXECUTABLE = 'executable',
  OTHER = 'other',
}

/**
 * Programming languages (for code detection)
 */
export enum ProgrammingLanguage {
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  PYTHON = 'python',
  JAVA = 'java',
  CSHARP = 'csharp',
  CPP = 'cpp',
  C = 'c',
  GO = 'go',
  RUST = 'rust',
  PHP = 'php',
  RUBY = 'ruby',
  SWIFT = 'swift',
  KOTLIN = 'kotlin',
  DART = 'dart',
  POWERSHELL = 'powershell',
  BASH = 'bash',
  SQL = 'sql',
  HTML = 'html',
  CSS = 'css',
  JSON = 'json',
  YAML = 'yaml',
  XML = 'xml',
  MARKDOWN = 'markdown',
  TOML = 'toml',
  INI = 'ini',
  UNKNOWN = 'unknown',
}

/**
 * Data formats
 */
export enum DataFormat {
  JSON = 'json',
  XML = 'xml',
  YAML = 'yaml',
  CSV = 'csv',
  TSV = 'tsv',
  TOML = 'toml',
  INI = 'ini',
  PROPERTIES = 'properties',
  PLIST = 'plist',
  PROTOBUF = 'protobuf',
}

/**
 * Text content types
 */
export enum TextType {
  PLAIN = 'plain',
  EMAIL = 'email',
  URL = 'url',
  PROMPT = 'prompt',
  COMMAND = 'command',
  LOG = 'log',
  ERROR = 'error',
  CONFIG = 'config',
  LICENSE = 'license',
  README = 'readme',
  DOCUMENTATION = 'documentation',
}

// ==================== UI ENUMS ====================

/**
 * Application themes
 */
export enum Theme {
  DARK = 'dark',
  LIGHT = 'light',
  SYSTEM = 'system',
  CUSTOM = 'custom',
}

/**
 * UI view modes
 */
export enum ViewMode {
  GRID = 'grid',
  LIST = 'list',
  DETAIL = 'detail',
  COMPACT = 'compact',
  EXPANDED = 'expanded',
  PREVIEW = 'preview',
}

/**
 * UI component states
 */
export enum ComponentState {
  DEFAULT = 'default',
  HOVER = 'hover',
  FOCUSED = 'focused',
  ACTIVE = 'active',
  DISABLED = 'disabled',
  LOADING = 'loading',
  ERROR = 'error',
  SUCCESS = 'success',
  WARNING = 'warning',
}

/**
 * Animation easing functions
 */
export enum EasingFunction {
  LINEAR = 'linear',
  EASE_IN = 'ease-in',
  EASE_OUT = 'ease-out',
  EASE_IN_OUT = 'ease-in-out',
  SMOOTH_STEP = 'smooth-step',
  BOUNCE = 'bounce',
  ELASTIC = 'elastic',
  SPRING = 'spring',
}

// ==================== SYSTEM ENUMS ====================

/**
 * Operating systems supported
 */
export enum OperatingSystem {
  WINDOWS = 'windows',
  MACOS = 'macos',
  LINUX = 'linux',
  UNKNOWN = 'unknown',
}

/**
 * Architecture types
 */
export enum Architecture {
  X64 = 'x64',
  ARM64 = 'arm64',
  IA32 = 'ia32',
  ARM = 'arm',
  UNKNOWN = 'unknown',
}

/**
 * Application update channels
 */
export enum UpdateChannel {
  STABLE = 'stable',
  BETA = 'beta',
  ALPHA = 'alpha',
  DEV = 'dev',
  CUSTOM = 'custom',
}

/**
 * Application lifecycle states
 */
export enum AppLifecycleState {
  BOOTING = 'booting',
  READY = 'ready',
  ACTIVE = 'active',
  IDLE = 'idle',
  BACKGROUND = 'background',
  SUSPENDED = 'suspended',
  SHUTTING_DOWN = 'shutting_down',
  TERMINATED = 'terminated',
}

// ==================== STORAGE ENUMS ====================

/**
 * Database table names
 */
export enum DatabaseTable {
  CLIPBOARD_HISTORY = 'clipboard_history',
  SETTINGS = 'settings',
  TAGS = 'tags',
  AI_CACHE = 'ai_cache',
  SECURITY_EVENTS = 'security_events',
  USER_SESSIONS = 'user_sessions',
  BACKUP_METADATA = 'backup_metadata',
}

/**
 * Storage engines
 */
export enum StorageEngine {
  SQLITE = 'sqlite',
  INDEXEDDB = 'indexeddb',
  LOCAL_STORAGE = 'local_storage',
  FILE_SYSTEM = 'file_system',
  MEMORY = 'memory',
}

/**
 * Backup frequency options
 */
export enum BackupFrequency {
  HOURLY = 'hourly',
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
  MANUAL = 'manual',
}

/**
 * Export formats
 */
export enum ExportFormat {
  JSON = 'json',
  CSV = 'csv',
  SQL = 'sql',
  HTML = 'html',
  MARKDOWN = 'markdown',
  PLAIN_TEXT = 'plain_text',
}

// ==================== ERROR ENUMS ====================

/**
 * Error categories
 */
export enum ErrorCategory {
  CLIPBOARD = 'clipboard',
  AI = 'ai',
  SECURITY = 'security',
  STORAGE = 'storage',
  UI = 'ui',
  NETWORK = 'network',
  SYSTEM = 'system',
  VALIDATION = 'validation',
  UNKNOWN = 'unknown',
}
