/* Minimal i18n auto-generated by patch script - extend as needed */
export type Lang = "en"|"ar";
export const TRANSLATIONS: Record<Lang, Record<string,string>> = {
  en: { "cache.init":"Initializing CacheManager" },
  ar: { "cache.init":"جارٍ تهيئة مدير التخزين المؤقت" }
};
export function getSystemLocale(): Lang {
  try { const e = require("electron"); const l = e?.app?.getLocale?.()?.slice(0,2); if(l==="ar") return "ar"; } catch {}
  const env = process.env.LANG || process.env.LC_ALL || process.env.LANGUAGE || "";
  return (env||"").toString().slice(0,2).toLowerCase() === "ar" ? "ar":"en";
}
export function t(key:string, lang?:Lang) { const use = lang || getSystemLocale(); return TRANSLATIONS[use][key] ?? TRANSLATIONS["en"][key]; }
export default { t, getSystemLocale };
