/**
 * Knoux Clipboard AI - TypeScript Type Definitions
 * Central type definitions for the entire application
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import { CONTENT_TYPES, ERROR_CODES, UI } from './constants';

// ==================== CORE TYPES ====================

/**
 * Represents a clipboard history item
 */
export interface ClipboardItem {
  id: string;
  content: string;
  contentType: ClipboardContentType;
  classifiedType?: ContentClassification;
  sourceApp?: string;
  timestamp: number;
  sizeBytes: number;
  preview: string;
  metadata: ClipboardMetadata;
  tags: string[];
  isSensitive: boolean;
  isEncrypted: boolean;
  aiAnalysis?: AIAnalysis;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Clipboard content type (from supported types)
 */
export type ClipboardContentType = 
  | 'text'
  | 'html'
  | 'rtf'
  | 'image';

/**
 * Detailed metadata about clipboard content
 */
export interface ClipboardMetadata {
  language?: string;
  lineCount?: number;
  charCount?: number;
  wordCount?: number;
  hasUrls?: boolean;
  hasEmails?: boolean;
  hasCode?: boolean;
  mimeType?: string;
  encoding?: string;
  sourceProcess?: string;
  sourceWindow?: string;
  filePath?: string;
}

/**
 * Content classification result
 */
export interface ContentClassification {
  primaryType: ContentTypeKey;
  secondaryTypes: ContentTypeKey[];
  confidence: number;
  language?: string;
  framework?: string;
  isSensitive: boolean;
  sensitiveType?: SensitiveType;
  patterns: ClassificationPattern[];
}

/**
 * Content type key from CONTENT_TYPES
 */
export type ContentTypeKey = 
  | keyof typeof CONTENT_TYPES.CODE
  | keyof typeof CONTENT_TYPES.TEXT
  | keyof typeof CONTENT_TYPES.SENSITIVE
  | keyof typeof CONTENT_TYPES.MEDIA;

/**
 * Sensitive data type
 */
export type SensitiveType = 
  | 'api_key'
  | 'password'
  | 'token'
  | 'credit_card'
  | 'private_key'
  | 'personal_info'
  | 'unknown';

/**
 * Pattern detected during classification
 */
export interface ClassificationPattern {
  type: string;
  pattern: string;
  confidence: number;
  location: TextLocation;
}

/**
 * Location within text
 */
export interface TextLocation {
  start: number;
  end: number;
  line: number;
  column: number;
}

// ==================== AI TYPES ====================

/**
 * AI analysis result for clipboard content
 */
export interface AIAnalysis {
  id: string;
  itemId: string;
  summary?: string;
  suggestions: AISuggestion[];
  complexity: number; // 0-100
  quality: number; // 0-100
  potentialIssues: string[];
  improvements: string[];
  similarPastItems: string[];
  generatedAt: Date;
  modelUsed: string;
  processingTimeMs: number;
}

/**
 * AI suggestion for clipboard content
 */
export interface AISuggestion {
  id: string;
  type: SuggestionType;
  title: string;
  description: string;
  action?: SuggestionAction;
  priority: SuggestionPriority;
  confidence: number;
  codeExample?: string;
  applyAutomatically: boolean;
}

/**
 * Type of AI suggestion
 */
export type SuggestionType = 
  | 'code_improvement'
  | 'security_fix'
  | 'formatting'
  | 'optimization'
  | 'explanation'
  | 'translation'
  | 'summarization'
  | 'prompt_enhancement'
  | 'error_detection'
  | 'best_practice';

/**
 * Priority level for suggestions
 */
export type SuggestionPriority = 
  | 'critical'
  | 'high'
  | 'medium'
  | 'low'
  | 'info';

/**
 * Action to apply suggestion
 */
export interface SuggestionAction {
  type: 'replace' | 'append' | 'prepend' | 'transform' | 'execute';
  content?: string;
  command?: string;
  parameters?: Record<string, any>;
}

// ==================== SECURITY TYPES ====================

/**
 * Security scan result
 */
export interface SecurityScan {
  threats: SecurityThreat[];
  warnings: SecurityWarning[];
  recommendations: string[];
  scanTime: Date;
  isSafe: boolean;
  riskLevel: RiskLevel;
}

/**
 * Security threat detected
 */
export interface SecurityThreat {
  type: ThreatType;
  severity: ThreatSeverity;
  description: string;
  location?: TextLocation;
  content?: string;
  remediation: string;
  detectedAt: Date;
}

/**
 * Type of security threat
 */
export type ThreatType = 
  | 'api_key_exposed'
  | 'password_exposed'
  | 'token_leak'
  | 'malicious_code'
  | 'sql_injection'
  | 'xss'
  | 'command_injection'
  | 'path_traversal'
  | 'regex_dos'
  | 'hardcoded_secret';

/**
 * Threat severity level
 */
export type ThreatSeverity = 
  | 'critical'
  | 'high'
  | 'medium'
  | 'low';

/**
 * Security warning (less severe than threat)
 */
export interface SecurityWarning {
  type: string;
  description: string;
  suggestion: string;
}

/**
 * Risk level assessment
 */
export type RiskLevel = 
  | 'none'
  | 'low'
  | 'medium'
  | 'high'
  | 'critical';

// ==================== STORAGE TYPES ====================

/**
 * Database schema for clipboard history
 */
export interface HistorySchema {
  id: string;
  content: string;
  content_type: string;
  classified_type?: string;
  source_app?: string;
  timestamp: number;
  size_bytes: number;
  preview: string;
  metadata: string; // JSON string
  tags: string; // JSON string
  is_sensitive: boolean;
  is_encrypted: boolean;
  ai_analysis?: string; // JSON string
  created_at: string;
  updated_at: string;
}

/**
 * Application settings schema
 */
export interface SettingsSchema {
  id: string;
  category: string;
  key: string;
  value: string;
  type: 'string' | 'number' | 'boolean' | 'object' | 'array';
  updated_at: string;
}

/**
 * Tag schema
 */
export interface TagSchema {
  id: string;
  name: string;
  color: string;
  icon: string;
  description?: string;
  created_at: string;
  item_count: number;
}

/**
 * AI cache schema
 */
export interface AICacheSchema {
  id: string;
  content_hash: string;
  analysis: string; // JSON string
  created_at: string;
  expires_at?: string;
}

// ==================== UI TYPES ====================

/**
 * Application theme
 */
export type Theme = typeof UI.THEMES[keyof typeof UI.THEMES];

/**
 * UI state for clipboard list
 */
export interface ClipboardUIState {
  items: ClipboardItem[];
  filteredItems: ClipboardItem[];
  selectedItemId?: string;
  searchQuery: string;
  filter: ClipboardFilter;
  sortBy: SortField;
  sortOrder: SortOrder;
  isLoading: boolean;
  error?: Error;
}

/**
 * Filter criteria for clipboard items
 */
export interface ClipboardFilter {
  contentType?: ClipboardContentType[];
  classifiedType?: ContentTypeKey[];
  dateRange?: {
    start: Date;
    end: Date;
  };
  tags?: string[];
  sensitiveOnly?: boolean;
  withAiAnalysis?: boolean;
  minSizeBytes?: number;
  maxSizeBytes?: number;
}

/**
 * Field to sort by
 */
export type SortField = 
  | 'timestamp'
  | 'sizeBytes'
  | 'contentType'
  | 'classifiedType'
  | 'aiConfidence';

/**
 * Sort order
 */
export type SortOrder = 'asc' | 'desc';

/**
 * Notification configuration
 */
export interface Notification {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  duration: number;
  priority: NotificationPriority;
  action?: NotificationAction;
  createdAt: Date;
  read: boolean;
}

/**
 * Type of notification
 */
export type NotificationType = 
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'security'
  | 'ai';

/**
 * Notification priority
 */
export type NotificationPriority = 
  | 'low'
  | 'normal'
  | 'high'
  | 'urgent';

/**
 * Action for notification
 */
export interface NotificationAction {
  label: string;
  handler: () => void;
}

// ==================== IPC TYPES ====================

/**
 * IPC request structure
 */
export interface IPCRequest<T = any> {
  id: string;
  channel: string;
  method: string;
  params: T;
  timestamp: number;
}

/**
 * IPC response structure
 */
export interface IPCResponse<T = any> {
  id: string;
  channel: string;
  method: string;
  result?: T;
  error?: IPCError;
  timestamp: number;
}

/**
 * IPC error structure
 */
export interface IPCError {
  code: keyof typeof ERROR_CODES | string;
  message: string;
  details?: any;
  stack?: string;
}

/**
 * IPC event structure
 */
export interface IPCEvent<T = any> {
  type: string;
  data: T;
  timestamp: number;
}

// ==================== SETTINGS TYPES ====================

/**
 * Complete application settings
 */
export interface AppSettings {
  clipboard: ClipboardSettings;
  ai: AISettings;
  security: SecuritySettings;
  ui: UISettings;
  notifications: NotificationSettings;
  system: SystemSettings;
}

/**
 * Clipboard module settings
 */
export interface ClipboardSettings {
  enableMonitoring: boolean;
  maxHistoryItems: number;
  autoClearSensitive: boolean;
  autoClearMinutes: number;
  captureImages: boolean;
  captureHtml: boolean;
  captureRtf: boolean;
  excludeApps: string[];
  maxItemSizeKB: number;
  backupIntervalHours: number;
}

/**
 * AI module settings
 */
export interface AISettings {
  enabled: boolean;
  useLocalModel: boolean;
  useCloudApi: boolean;
  apiKey: string;
  apiEndpoint: string;
  analyzeCode: boolean;
  analyzeText: boolean;
  detectSensitive: boolean;
  cacheResults: boolean;
  cacheDurationMinutes: number;
  maxContextLength: number;
  modelPath: string;
  confidenceThreshold: number;
}

/**
 * Security module settings
 */
export interface SecuritySettings {
  encryptSensitive: boolean;
  requirePassword: boolean;
  password: string;
  autoLockMinutes: number;
  showSecurityAlerts: boolean;
  sandboxExternalContent: boolean;
  allowedDomains: string[];
  blockedPatterns: string[];
  encryptionAlgorithm: string;
  keyDerivationIterations: number;
}

/**
 * UI module settings
 */
export interface UISettings {
  theme: Theme;
  fontSize: number;
  fontFamily: string;
  showTrayIcon: boolean;
  minimizeToTray: boolean;
  startMinimized: boolean;
  animationsEnabled: boolean;
  hotkeysEnabled: boolean;
  hotkeys: Record<string, string>;
  windowBounds: WindowBounds;
  language: string;
}

/**
 * Window bounds
 */
export interface WindowBounds {
  x: number;
  y: number;
  width: number;
  height: number;
  maximized: boolean;
}

/**
 * Notification settings
 */
export interface NotificationSettings {
  enabled: boolean;
  sound: boolean;
  duration: number;
  position: NotificationPosition;
  showOnClipboardUpdate: boolean;
  showOnAiAnalysis: boolean;
  showOnSecurityAlert: boolean;
  doNotDisturb: boolean;
  doNotDisturbStart: string;
  doNotDisturbEnd: string;
}

/**
 * Notification position
 */
export type NotificationPosition = 
  | 'top-left'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-right'
  | 'center';

/**
 * System settings
 */
export interface SystemSettings {
  startOnLogin: boolean;
  checkForUpdates: boolean;
  updateChannel: UpdateChannel;
  analyticsEnabled: boolean;
  crashReportsEnabled: boolean;
  logsRetentionDays: number;
  performanceMode: PerformanceMode;
}

/**
 * Update channel
 */
export type UpdateChannel = 
  | 'stable'
  | 'beta'
  | 'alpha';

/**
 * Performance mode
 */
export type PerformanceMode = 
  | 'power-saver'
  | 'balanced'
  | 'performance';

// ==================== EVENT TYPES ====================

/**
 * Clipboard event
 */
export interface ClipboardEvent {
  type: 'added' | 'updated' | 'deleted' | 'cleared';
  item?: ClipboardItem;
  items?: ClipboardItem[];
  timestamp: number;
}

/**
 * AI event
 */
export interface AIEvent {
  type: 'analysis_started' | 'analysis_completed' | 'suggestion_generated' | 'error';
  itemId?: string;
  analysis?: AIAnalysis;
  error?: Error;
  timestamp: number;
}

/**
 * Security event
 */
export interface SecurityEvent {
  type: 'threat_detected' | 'warning_generated' | 'scan_completed' | 'encryption_applied';
  threat?: SecurityThreat;
  warning?: SecurityWarning;
  scan?: SecurityScan;
  itemId?: string;
  timestamp: number;
}

/**
 * System event
 */
export interface SystemEvent {
  type: 'app_started' | 'app_paused' | 'app_resumed' | 'app_stopping' | 'update_available';
  data?: any;
  timestamp: number;
}

// ==================== UTILITY TYPES ====================

/**
 * Result type for operations that can succeed or fail
 */
export type Result<T, E = Error> = 
  | { success: true; data: T }
  | { success: false; error: E };

/**
 * Async result type
 */
export type AsyncResult<T, E = Error> = Promise<Result<T, E>>;

/**
 * Partial but deep
 */
export type DeepPartial<T> = T extends object ? {
  [P in keyof T]?: DeepPartial<T[P]>;
} : T;

/**
 * Make specific properties optional
 */
export type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

/**
 * Make specific properties required
 */
export type Required<T, K extends keyof T> = T & {
  [P in K]-?: T[P];
};

/**
 * Nullable version of type
 */
export type Nullable<T> = T | null | undefined;

// ==================== API RESPONSE TYPES ====================

/**
 * Standard API response
 */
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  timestamp: number;
  requestId: string;
}

/**
 * Paginated response
 */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

// ==================== EXPORT ALL TYPES ====================

export type {
  ClipboardItem as IClipboardItem,
  ContentClassification as IContentClassification,
  AIAnalysis as IAIAnalysis,
  SecurityScan as ISecurityScan,
  AppSettings as IAppSettings,
};
