/**
 * Knoux Clipboard AI - AI Prompt Library
 * Pre-defined prompt templates for content enhancement and analysis
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import { llog } from '../../shared/localized-logger';
import { CONTENT_TYPES } from '../../shared/constants';
import { ProgrammingLanguage, TextType } from '../../shared/enums';
import { EnhancementOptions } from './enhancer';

/**
 * Prompt template configuration
 */
export interface PromptTemplate {
  id: string;
  name: string;
  description: string;
  category: PromptCategory;
  template: string;
  variables: string[];
  version: string;
  author?: string;
  tags: string[];
  usageCount: number;
  lastUsed?: Date;
  successRate?: number;
}

/**
 * Prompt categories
 */
export type PromptCategory = 
  | 'code_enhancement'
  | 'text_enhancement'
  | 'prompt_enhancement'
  | 'code_analysis'
  | 'text_analysis'
  | 'security_analysis'
  | 'summarization'
  | 'translation'
  | 'explanation'
  | 'optimization';

/**
 * Prompt variable replacement
 */
export interface PromptVariables {
  [key: string]: string | number | boolean;
}

/**
 * Prompt execution result
 */
export interface PromptExecutionResult {
  templateId: string;
  input: string;
  output: string;
  variablesUsed: PromptVariables;
  processingTimeMs: number;
  success: boolean;
  error?: string;
  metadata: PromptMetadata;
}

/**
 * Prompt metadata
 */
export interface PromptMetadata {
  tokenCount: number;
  variableCount: number;
  category: PromptCategory;
  templateVersion: string;
  executionTimestamp: Date;
}

export class PromptLibrary {
  private logger = createLogger({ module: 'prompt-library' });
  private templates: Map<string, PromptTemplate> = new Map();
  private executionHistory: PromptExecutionResult[] = [];
  private isInitialized = false;
  private readonly maxHistorySize = 1000;

  constructor() {
    this.initializeDefaultTemplates();
  }

  /**
   * Initialize prompt library with default templates
   */
  private initializeDefaultTemplates(): void {
    this.llog.info('Initializing prompt library with default templates');
    
    // Code enhancement templates
    this.addTemplate({
      id: 'code_enhance_js_001',
      name: 'JavaScript Code Enhancer',
      description: 'Enhances JavaScript code for readability, performance, and best practices',
      category: 'code_enhancement',
      template: You are an expert JavaScript developer. Analyze and improve the following code:

## Original Code:
\\\javascript
{code}
\\\

## Improvement Requirements:
1. Fix any syntax errors or bugs
2. Improve code readability and maintainability
3. Apply JavaScript best practices
4. Optimize for performance where possible
5. Add appropriate comments for complex logic
6. Ensure consistent formatting and style
{tone_instruction}
{complexity_instruction}

## Enhanced Code:
Provide only the enhanced JavaScript code without explanations.,
      variables: ['code', 'tone_instruction', 'complexity_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['javascript', 'code', 'enhancement', 'best-practices'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'code_enhance_py_001',
      name: 'Python Code Enhancer',
      description: 'Enhances Python code for readability, performance, and PEP 8 compliance',
      category: 'code_enhancement',
      template: You are an expert Python developer. Analyze and improve the following code:

## Original Code:
\\\python
{code}
\\\

## Improvement Requirements:
1. Fix syntax errors and bugs
2. Apply PEP 8 style guide
3. Improve code readability and maintainability
4. Add type hints where appropriate
5. Optimize performance (time/space complexity)
6. Add docstrings for functions and classes
{tone_instruction}
{complexity_instruction}

## Enhanced Code:
Provide only the enhanced Python code without explanations.,
      variables: ['code', 'tone_instruction', 'complexity_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['python', 'code', 'enhancement', 'pep8'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'code_enhance_ps_001',
      name: 'PowerShell Script Enhancer',
      description: 'Enhances PowerShell scripts for security, readability, and best practices',
      category: 'code_enhancement',
      template: You are an expert PowerShell developer. Analyze and improve the following script:

## Original Script:
\\\powershell
{code}
\\\

## Improvement Requirements:
1. Fix syntax errors and bugs
2. Apply PowerShell best practices and style guidelines
3. Improve script readability and maintainability
4. Add proper error handling (try/catch)
5. Add comment-based help for functions
6. Optimize for performance and security
{tone_instruction}
{complexity_instruction}
{security_instruction}

## Enhanced Script:
Provide only the enhanced PowerShell script without explanations.,
      variables: ['code', 'tone_instruction', 'complexity_instruction', 'security_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['powershell', 'script', 'enhancement', 'security'],
      usageCount: 0,
    });

    // Text enhancement templates
    this.addTemplate({
      id: 'text_enhance_general_001',
      name: 'General Text Enhancer',
      description: 'Enhances general text for clarity, conciseness, and professionalism',
      category: 'text_enhancement',
      template: You are an expert editor. Improve the following text:

## Original Text:
{text}

## Improvement Requirements:
1. Improve clarity and readability
2. Fix grammar and spelling errors
3. Make the text more concise without losing meaning
4. Enhance flow and structure
5. Adjust tone to be {tone}
6. Ensure professional language
{include_examples_instruction}
{max_length_instruction}

## Enhanced Text:
Provide only the enhanced text without explanations.,
      variables: ['text', 'tone', 'include_examples_instruction', 'max_length_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['text', 'enhancement', 'editing', 'professional'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'text_enhance_email_001',
      name: 'Email Text Enhancer',
      description: 'Enhances email content for professionalism and effectiveness',
      category: 'text_enhancement',
      template: You are an expert email writer. Improve the following email:

## Original Email:
{text}

## Improvement Requirements:
1. Improve subject line (if provided)
2. Enhance opening and closing
3. Make content clear and concise
4. Ensure professional tone
5. Add proper formatting
6. Include clear call-to-action if needed
7. Check for appropriate salutations
{tone_instruction}
{max_length_instruction}

## Enhanced Email:
Provide only the enhanced email without explanations.,
      variables: ['text', 'tone_instruction', 'max_length_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['email', 'text', 'enhancement', 'professional'],
      usageCount: 0,
    });

    // Prompt enhancement templates
    this.addTemplate({
      id: 'prompt_enhance_general_001',
      name: 'AI Prompt Enhancer',
      description: 'Enhances AI prompts for clarity, specificity, and effectiveness',
      category: 'prompt_enhancement',
      template: You are an expert prompt engineer. Improve the following AI prompt:

## Original Prompt:
{prompt}

## Analysis Criteria:
1. Clarity: Is the prompt clear and unambiguous?
2. Specificity: Does it provide enough detail and context?
3. Structure: Is it well-organized and easy to follow?
4. Tone: Is the tone appropriate for the task?
5. Completeness: Does it include all necessary information?

## Enhancement Guidelines:
- Make the prompt more specific and detailed
- Add context if missing
- Improve structure and organization
- Clarify ambiguous instructions
- Add examples if helpful
- Ensure appropriate tone ({tone})

## Enhanced Prompt:
Provide only the enhanced prompt without explanations.,
      variables: ['prompt', 'tone'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['prompt', 'enhancement', 'ai', 'clarity'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'prompt_enhance_codegen_001',
      name: 'Code Generation Prompt Enhancer',
      description: 'Enhances prompts for code generation tasks',
      category: 'prompt_enhancement',
      template: You are an expert in code generation prompts. Improve the following prompt:

## Original Prompt:
{prompt}

## Enhancement Requirements:
1. Specify programming language: {language}
2. Add requirements for:
   - Input/output format
   - Error handling
   - Performance constraints
   - Security considerations
   - Testing requirements
3. Include example inputs/outputs if helpful
4. Specify code style and conventions
5. Add edge cases to consider
{complexity_instruction}

## Enhanced Prompt:
Provide only the enhanced prompt without explanations.,
      variables: ['prompt', 'language', 'complexity_instruction'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['prompt', 'code-generation', 'enhancement'],
      usageCount: 0,
    });

    // Code analysis templates
    this.addTemplate({
      id: 'code_analysis_security_001',
      name: 'Code Security Analyzer',
      description: 'Analyzes code for security vulnerabilities and best practices',
      category: 'security_analysis',
      template: You are a security expert. Analyze the following code for security issues:

## Code to Analyze:
\\\{language}
{code}
\\\

## Security Analysis Checklist:
1. Input validation and sanitization
2. Authentication and authorization
3. Data encryption and protection
4. Error handling and information leakage
5. Dependency security
6. API security (if applicable)
7. Common vulnerabilities (XSS, SQLi, CSRF, etc.)

## Analysis Format:
For each issue found, provide:
- Issue Type: [Vulnerability Type]
- Severity: [Critical/High/Medium/Low]
- Location: [Line numbers or function names]
- Description: [Brief description]
- Recommendation: [How to fix]

## Security Report:
Provide a comprehensive security analysis report.,
      variables: ['code', 'language'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['security', 'analysis', 'code', 'vulnerability'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'code_analysis_performance_001',
      name: 'Code Performance Analyzer',
      description: 'Analyzes code for performance issues and optimization opportunities',
      category: 'code_analysis',
      template: You are a performance optimization expert. Analyze the following code:

## Code to Analyze:
\\\{language}
{code}
\\\

## Performance Analysis Areas:
1. Time complexity analysis
2. Space complexity analysis
3. Memory usage patterns
4. I/O operations efficiency
5. Algorithm optimization opportunities
6. Database query optimization (if applicable)
7. Network call optimization (if applicable)

## Performance Report:
Provide specific optimization recommendations with:
- Issue: [Performance problem]
- Impact: [Estimated performance gain]
- Solution: [Optimization approach]
- Code Example: [Optimized code snippet]

Focus on practical, actionable improvements.,
      variables: ['code', 'language'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['performance', 'analysis', 'optimization', 'code'],
      usageCount: 0,
    });

    // Summarization templates
    this.addTemplate({
      id: 'summarize_text_001',
      name: 'Text Summarizer',
      description: 'Summarizes long text into concise version',
      category: 'summarization',
      template: Summarize the following text:

## Original Text:
{text}

## Summary Requirements:
- Length: Approximately {max_length} words
- Maintain key information and main points
- Preserve important names, dates, and numbers
- Use clear, concise language
- Capture the overall tone and intent

## Summary:
Provide only the summary without additional text.,
      variables: ['text', 'max_length'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['summarization', 'text', 'compression'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'summarize_code_001',
      name: 'Code Documentation Generator',
      description: 'Generates documentation summaries for code',
      category: 'summarization',
      template: Generate comprehensive documentation for the following code:

## Code:
\\\{language}
{code}
\\\

## Documentation Requirements:
1. Overview: What does this code do?
2. Functions/Methods: List and describe each
3. Parameters: Document all parameters
4. Returns: Document return values
5. Examples: Provide usage examples
6. Dependencies: List any dependencies
7. Notes: Any important implementation details

## Documentation:
Provide well-structured documentation in markdown format.,
      variables: ['code', 'language'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['documentation', 'code', 'summarization'],
      usageCount: 0,
    });

    // Explanation templates
    this.addTemplate({
      id: 'explain_code_001',
      name: 'Code Explainer',
      description: 'Explains code in simple terms for different audiences',
      category: 'explanation',
      template: Explain the following code for a {audience} audience:

## Code:
\\\{language}
{code}
\\\

## Explanation Requirements:
- Audience Level: {audience}
- Cover: What the code does, how it works, why it's written this way
- Highlight: Key algorithms, data structures, or patterns
- Simplify: Complex concepts without losing accuracy
- Include: Practical implications and use cases

## Explanation:
Provide a clear, audience-appropriate explanation.,
      variables: ['code', 'language', 'audience'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['explanation', 'code', 'education'],
      usageCount: 0,
    });

    this.addTemplate({
      id: 'explain_error_001',
      name: 'Error Message Explainer',
      description: 'Explains error messages and suggests fixes',
      category: 'explanation',
      template: Explain this error message and suggest fixes:

## Error Message:
{error}

## Context (if available):
{context}

## Explanation Requirements:
1. Plain English explanation of the error
2. Common causes of this error
3. Step-by-step debugging suggestions
4. Code fixes or workarounds
5. Prevention tips for the future

## Explanation and Fixes:
Provide a comprehensive explanation and actionable fixes.,
      variables: ['error', 'context'],
      version: '1.0.0',
      author: 'Knoux AI',
      tags: ['error', 'explanation', 'debugging'],
      usageCount: 0,
    });

    this.llog.info(Loaded  default templates);
  }

  /**
   * Initialize the prompt library
   */
  public async initialize(): Promise<void> {
    if (this.isInitialized) {
      return;
    }

    this.llog.info('Initializing prompt library');
    
    try {
      // Load custom templates from storage if available
      await this.loadCustomTemplates();
      
      this.isInitialized = true;
      this.llog.info('Prompt library initialized successfully', {
        templateCount: this.templates.size,
        categories: this.getTemplateCategories(),
      });
    } catch (error) {
      this.llog.error('Failed to initialize prompt library', error as Error);
      throw error;
    }
  }

  /**
   * Load custom templates from storage
   */
  private async loadCustomTemplates(): Promise<void> {
    // In a real implementation, this would load from a database or file
    // For now, we'll just log that we would load custom templates
    this.llog.debug('Would load custom templates from storage');
  }

  /**
   * Add a new template to the library
   */
  public addTemplate(template: PromptTemplate): void {
    if (this.templates.has(template.id)) {
      this.llog.warn('Template already exists, updating', { id: template.id });
    }
    
    this.templates.set(template.id, template);
    this.llog.debug('Template added/updated', { id: template.id, name: template.name });
  }

  /**
   * Remove a template from the library
   */
  public removeTemplate(templateId: string): boolean {
    const existed = this.templates.delete(templateId);
    if (existed) {
      this.llog.debug('Template removed', { id: templateId });
    }
    return existed;
  }

  /**
   * Get a template by ID
   */
  public getTemplate(templateId: string): PromptTemplate | undefined {
    const template = this.templates.get(templateId);
    if (template) {
      // Update usage statistics
      template.usageCount++;
      template.lastUsed = new Date();
    }
    return template;
  }

  /**
   * Get all templates
   */
  public getAllTemplates(): PromptTemplate[] {
    return Array.from(this.templates.values());
  }

  /**
   * Get templates by category
   */
  public getTemplatesByCategory(category: PromptCategory): PromptTemplate[] {
    return Array.from(this.templates.values()).filter(t => t.category === category);
  }

  /**
   * Get templates by tag
   */
  public getTemplatesByTag(tag: string): PromptTemplate[] {
    return Array.from(this.templates.values()).filter(t => t.tags.includes(tag));
  }

  /**
   * Get all template categories
   */
  public getTemplateCategories(): PromptCategory[] {
    const categories = new Set<PromptCategory>();
    this.templates.forEach(template => categories.add(template.category));
    return Array.from(categories);
  }

  /**
   * Get code enhancement prompt
   */
  public getCodeEnhancementPrompt(
    language: ProgrammingLanguage,
    options: EnhancementOptions
  ): string {
    let templateId: string;
    
    switch (language) {
      case ProgrammingLanguage.JAVASCRIPT:
      case ProgrammingLanguage.TYPESCRIPT:
        templateId = 'code_enhance_js_001';
        break;
      case ProgrammingLanguage.PYTHON:
        templateId = 'code_enhance_py_001';
        break;
      case ProgrammingLanguage.POWERSHELL:
        templateId = 'code_enhance_ps_001';
        break;
      default:
        templateId = 'code_enhance_js_001'; // Default to JavaScript
    }
    
    const template = this.getTemplate(templateId);
    if (!template) {
      throw new Error(Template not found: );
    }
    
    const variables: PromptVariables = {
      code: '{code}', // Will be replaced by caller
      tone_instruction: this.getToneInstruction(options.tone),
      complexity_instruction: this.getComplexityInstruction(options.complexityLevel),
    };
    
    if (templateId === 'code_enhance_ps_001' && options.securityCheck) {
      variables.security_instruction = '7. Ensure security best practices are followed';
    }
    
    return this.renderTemplate(template.template, variables);
  }

  /**
   * Get text enhancement prompt
   */
  public getTextEnhancementPrompt(
    textType: 'email' | 'document' | 'general',
    options: EnhancementOptions
  ): string {
    let templateId: string;
    
    switch (textType) {
      case 'email':
        templateId = 'text_enhance_email_001';
        break;
      default:
        templateId = 'text_enhance_general_001';
    }
    
    const template = this.getTemplate(templateId);
    if (!template) {
      throw new Error(Template not found: );
    }
    
    const variables: PromptVariables = {
      text: '{text}', // Will be replaced by caller
      tone: options.tone || 'professional',
      include_examples_instruction: options.includeExamples ? '7. Include relevant examples if helpful' : '',
      max_length_instruction: options.maxLength ? 8. Keep within  characters : '',
    };
    
    if (templateId === 'text_enhance_email_001') {
      variables.tone_instruction = Adjust tone to be ;
    }
    
    return this.renderTemplate(template.template, variables);
  }

  /**
   * Get prompt enhancement prompt
   */
  public getPromptEnhancementPrompt(options: EnhancementOptions): string {
    const templateId = options.targetLanguage ? 'prompt_enhance_codegen_001' : 'prompt_enhance_general_001';
    const template = this.getTemplate(templateId);
    
    if (!template) {
      throw new Error(Template not found: );
    }
    
    const variables: PromptVariables = {
      prompt: '{prompt}', // Will be replaced by caller
      tone: options.tone || 'clear and direct',
    };
    
    if (templateId === 'prompt_enhance_codegen_001') {
      variables.language = options.targetLanguage || ProgrammingLanguage.JAVASCRIPT;
      variables.complexity_instruction = options.complexityLevel 
        ? Complexity Level: 
        : '';
    }
    
    return this.renderTemplate(template.template, variables);
  }

  /**
   * Get tone instruction for prompt
   */
  private getToneInstruction(tone?: string): string {
    if (!tone) return '';
    
    const toneInstructions: Record<string, string> = {
      formal: 'Use formal, professional language',
      casual: 'Use casual, conversational language',
      technical: 'Use technical, precise language',
      creative: 'Use creative, expressive language',
    };
    
    return toneInstructions[tone] || Use  tone;
  }

  /**
   * Get complexity instruction for prompt
   */
  private getComplexityInstruction(complexityLevel?: string): string {
    if (!complexityLevel) return '';
    
    const complexityInstructions: Record<string, string> = {
      beginner: 'Make the code suitable for beginners (add comments, use simple patterns)',
      intermediate: 'Make the code suitable for intermediate developers',
      advanced: 'Use advanced patterns and optimizations where appropriate',
      expert: 'Use expert-level patterns, optimizations, and best practices',
    };
    
    return complexityInstructions[complexityLevel] || '';
  }

  /**
   * Render a template with variables
   */
  public renderTemplate(template: string, variables: PromptVariables): string {
    let rendered = template;
    
    for (const [key, value] of Object.entries(variables)) {
      const placeholder = {};
      rendered = rendered.replace(new RegExp(placeholder, 'g'), String(value));
    }
    
    // Remove any remaining undefined variables
    rendered = rendered.replace(/{[^{}]+}/g, '');
    
    return rendered;
  }

  /**
   * Execute a prompt template with content
   */
  public executeTemplate(
    templateId: string,
    content: string,
    additionalVariables: PromptVariables = {}
  ): string {
    const template = this.getTemplate(templateId);
    if (!template) {
      throw new Error(Template not found: );
    }
    
    // Prepare variables
    const variables: PromptVariables = {
      ...additionalVariables,
    };
    
    // Add content based on template variables
    if (template.variables.includes('code')) {
      variables.code = content;
    } else if (template.variables.includes('text')) {
      variables.text = content;
    } else if (template.variables.includes('prompt')) {
      variables.prompt = content;
    } else if (template.variables.includes('error')) {
      variables.error = content;
    }
    
    // Render the template
    return this.renderTemplate(template.template, variables);
  }

  /**
   * Search templates by keyword
   */
  public searchTemplates(keyword: string): PromptTemplate[] {
    const searchTerm = keyword.toLowerCase();
    
    return Array.from(this.templates.values()).filter(template => {
      return (
        template.name.toLowerCase().includes(searchTerm) ||
        template.description.toLowerCase().includes(searchTerm) ||
        template.tags.some(tag => tag.toLowerCase().includes(searchTerm)) ||
        template.category.toLowerCase().includes(searchTerm)
      );
    });
  }

  /**
   * Record prompt execution history
   */
  public recordExecution(result: PromptExecutionResult): void {
    this.executionHistory.unshift(result);
    
    // Limit history size
    if (this.executionHistory.length > this.maxHistorySize) {
      this.executionHistory = this.executionHistory.slice(0, this.maxHistorySize);
    }
    
    // Update template success rate
    const template = this.templates.get(result.templateId);
    if (template) {
      const previousSuccessRate = template.successRate || 0;
      const previousUsage = template.usageCount - 1;
      template.successRate = (previousSuccessRate * previousUsage + (result.success ? 1 : 0)) / template.usageCount;
    }
  }

  /**
   * Get execution history
   */
  public getExecutionHistory(limit?: number): PromptExecutionResult[] {
    return limit ? this.executionHistory.slice(0, limit) : this.executionHistory;
  }

  /**
   * Clear execution history
   */
  public clearExecutionHistory(): void {
    this.executionHistory = [];
    this.llog.debug('Execution history cleared');
  }

  /**
   * Export templates to JSON
   */
  public exportTemplates(): string {
    const exportData = {
      version: '1.0.0',
      exportDate: new Date().toISOString(),
      templateCount: this.templates.size,
      templates: Array.from(this.templates.values()),
    };
    
    return JSON.stringify(exportData, null, 2);
  }

  /**
   * Import templates from JSON
   */
  public importTemplates(json: string): number {
    try {
      const importData = JSON.parse(json);
      
      if (!importData.templates || !Array.isArray(importData.templates)) {
        throw new Error('Invalid template format');
      }
      
      let importedCount = 0;
      importData.templates.forEach((template: PromptTemplate) => {
        if (template.id && template.template) {
          this.addTemplate(template);
          importedCount++;
        }
      });
      
      this.llog.info('Templates imported successfully', { count: importedCount });
      return importedCount;
      
    } catch (error) {
      this.llog.error('Failed to import templates', error as Error);
      throw error;
    }
  }

  /**
   * Get library statistics
   */
  public getStatistics(): {
    totalTemplates: number;
    totalExecutions: number;
    categories: Record<string, number>;
    mostUsedTemplates: Array<{ id: string; name: string; usageCount: number }>;
  } {
    const categories: Record<string, number> = {};
    const mostUsed = Array.from(this.templates.values())
      .sort((a, b) => b.usageCount - a.usageCount)
      .slice(0, 5)
      .map(t => ({ id: t.id, name: t.name, usageCount: t.usageCount }));
    
    this.templates.forEach(template => {
      categories[template.category] = (categories[template.category] || 0) + 1;
    });
    
    return {
      totalTemplates: this.templates.size,
      totalExecutions: this.executionHistory.length,
      categories,
      mostUsedTemplates: mostUsed,
    };
  }

  /**
   * Check if library is ready
   */
  public isReady(): boolean {
    return this.isInitialized;
  }

  /**
   * Reset library to default state
   */
  public reset(): void {
    this.templates.clear();
    this.executionHistory = [];
    this.initializeDefaultTemplates();
    this.llog.info('Prompt library reset to defaults');
  }
}




