/**
 * Knoux Clipboard AI - AI Processor Component
 * Interactive interface for AI-powered content analysis, enhancement, and summarization
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Sparkles,
  Brain,
  Zap,
  Filter,
  Copy,
  Check,
  RotateCw,
  Download,
  Upload,
  Settings,
  HelpCircle,
  AlertCircle,
  X,
  Maximize2,
  Minimize2,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  MessageSquare,
  FileText,
  Code,
  Languages,
  Target,
  BarChart
} from 'lucide-react';
import { logger, createLogger } from '../../shared/logger';
import { useAI } from '../hooks/useAI';
import {
  AIAnalysis,
  AISuggestion,
  ContentClassification
} from '../../shared/types';
import {
  AIOperation,
  SuggestionCategory,
  ContentCategory
} from '../../shared/enums';

/**
 * Component props
 */
interface AIProcessorProps {
  initialContent?: string;
  clipboardItemId?: string;
  onContentProcessed?: (result: any) => void;
  onSuggestionApplied?: (suggestion: AISuggestion, content: string) => void;
  className?: string;
}

/**
 * Processing mode
 */
type ProcessingMode = 'analyze' | 'enhance' | 'summarize' | 'classify' | 'translate' | 'explain';

/**
 * Enhancement option
 */
interface EnhancementOption {
  id: string;
  label: string;
  description: string;
  icon: React.ReactNode;
  defaultEnabled: boolean;
}

export const AIProcessor: React.FC<AIProcessorProps> = ({
  initialContent = '',
  clipboardItemId,
  onContentProcessed,
  onSuggestionApplied,
  className = ''
}) => {
  const logger = createLogger({ module: 'AIProcessor' });
  const {
    analyzeContent,
    enhanceContent,
    classifyContent,
    summarizeContent,
    getStatus,
    isProcessing,
    getStats
  } = useAI();
  
  // State
  const [content, setContent] = useState(initialContent);
  const [processingMode, setProcessingMode] = useState<ProcessingMode>('analyze');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [analysis, setAnalysis] = useState<AIAnalysis | null>(null);
  const [suggestions, setSuggestions] = useState<AISuggestion[]>([]);
  const [classification, setClassification] = useState<ContentClassification | null>(null);
  const [enhancedContent, setEnhancedContent] = useState('');
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [enhancementOptions, setEnhancementOptions] = useState<EnhancementOption[]>([
    {
      id: 'improve-readability',
      label: 'Improve Readability',
      description: 'Make text easier to read and understand',
      icon: <Eye size={16} />,
      defaultEnabled: true
    },
    {
      id: 'fix-grammar',
      label: 'Fix Grammar',
      description: 'Correct spelling and grammatical errors',
      icon: <FileText size={16} />,
      defaultEnabled: true
    },
    {
      id: 'optimize-code',
      label: 'Optimize Code',
      description: 'Improve code structure and performance',
      icon: <Code size={16} />,
      defaultEnabled: true
    },
    {
      id: 'add-comments',
      label: 'Add Comments',
      description: 'Add explanatory comments to code',
      icon: <MessageSquare size={16} />,
      defaultEnabled: false
    },
    {
      id: 'security-check',
      label: 'Security Check',
      description: 'Identify security vulnerabilities',
      icon: <Lock size={16} />,
      defaultEnabled: true
    }
  ]);
  const [activeEnhancements, setActiveEnhancements] = useState<Set<string>>(
    new Set(enhancementOptions.filter(opt => opt.defaultEnabled).map(opt => opt.id))
  );
  const [processingHistory, setProcessingHistory] = useState<any[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(true);
  const [modelSettings, setModelSettings] = useState({
    temperature: 0.7,
    maxTokens: 1000,
    creativity: 'balanced' as 'conservative' | 'balanced' | 'creative'
  });
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamedContent, setStreamedContent] = useState('');
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  // Load clipboard content if item ID is provided
  useEffect(() => {
    if (clipboardItemId) {
      loadClipboardContent(clipboardItemId);
    }
  }, [clipboardItemId]);

  // Auto-scroll results
  useEffect(() => {
    if (resultsRef.current && (analysis || enhancedContent || summary)) {
      resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, [analysis, enhancedContent, summary]);

  // Load clipboard content
  const loadClipboardContent = async (itemId: string) => {
    try {
      const response = await window.knoux.getClipboardItem(itemId);
      if (response.success && response.data) {
        setContent(response.data.content);
        setSuccessMessage('Loaded content from clipboard history');
        setTimeout(() => setSuccessMessage(null), 3000);
      }
    } catch (error) {
      logger.error('Failed to load clipboard content', error as Error);
    }
  };

  // Process content
  const processContent = useCallback(async () => {
    if (!content.trim()) {
      setError('Please enter some content to process');
      return;
    }

    setLoading(true);
    setError(null);
    setAnalysis(null);
    setEnhancedContent('');
    setSummary('');
    setClassification(null);
    setSuggestions([]);

    try {
      logger.debug('Processing content', { mode: processingMode, contentLength: content.length });

      const startTime = Date.now();
      let result: any;

      switch (processingMode) {
        case 'analyze':
          result = await analyzeContent(content, {
            temperature: modelSettings.temperature,
            maxTokens: modelSettings.maxTokens
          });
          if (result.success) {
            const analysis: AIAnalysis = {
              id: `analysis_${Date.now()}`,
              itemId: clipboardItemId || '',
              summary: result.data.summary || 'Analysis completed',
              suggestions: result.data.suggestions || [],
              complexity: result.data.complexity || 50,
              quality: result.data.quality || 70,
              potentialIssues: result.data.potentialIssues || [],
              improvements: result.data.improvements || [],
              similarPastItems: result.data.similarPastItems || [],
              generatedAt: new Date(),
              modelUsed: result.data.modelUsed || 'default',
              processingTimeMs: Date.now() - startTime
            };
            setAnalysis(analysis);
            setSuggestions(analysis.suggestions);
          }
          break;

        case 'enhance':
          result = await enhanceContent(content, {
            enhancements: Array.from(activeEnhancements),
            temperature: modelSettings.temperature,
            creativity: modelSettings.creativity
          });
          if (result.success) {
            setEnhancedContent(result.data.enhanced);
            setSuggestions(result.data.suggestions || []);
          }
          break;

        case 'summarize':
          result = await summarizeContent(content, {
            compressionRatio: 0.3,
            format: 'bullet'
          });
          if (result.success) {
            setSummary(result.data.summary);
          }
          break;

        case 'classify':
          result = await classifyContent(content, {
            detailedAnalysis: true
          });
          if (result.success) {
            setClassification(result.data);
          }
          break;

        default:
          throw new Error(`Unsupported processing mode: ${processingMode}`);
      }

      if (result.success) {
        // Add to history
        setProcessingHistory(prev => [{
          mode: processingMode,
          content: content.substring(0, 100),
          timestamp: new Date(),
          result: result.data
        }, ...prev.slice(0, 9)]);

        setSuccessMessage(`${processingMode.charAt(0).toUpperCase() + processingMode.slice(1)} completed successfully`);
        setTimeout(() => setSuccessMessage(null), 3000);

        if (onContentProcessed) {
          onContentProcessed(result.data);
        }
      } else {
        throw new Error(result.error || 'Processing failed');
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      logger.error('Failed to process content', error as Error);
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  }, [content, processingMode, activeEnhancements, modelSettings, clipboardItemId]);

  // Stream content (simulated for now)
  const streamContent = async () => {
    if (!content.trim()) return;

    setIsStreaming(true);
    setStreamedContent('');
    setError(null);

    const words = content.split(' ');
    let currentIndex = 0;

    const streamInterval = setInterval(() => {
      if (currentIndex >= words.length) {
        clearInterval(streamInterval);
        setIsStreaming(false);
        setSuccessMessage('Streaming completed');
        setTimeout(() => setSuccessMessage(null), 2000);
        return;
      }

      setStreamedContent(prev => prev + (prev ? ' ' : '') + words[currentIndex]);
      currentIndex++;
    }, 50);
  };

  // Apply suggestion
  const applySuggestion = (suggestion: AISuggestion) => {
    if (suggestion.action) {
      switch (suggestion.action.type) {
        case 'replace':
          if (suggestion.action.content) {
            setContent(suggestion.action.content);
            setSuccessMessage(`Applied suggestion: ${suggestion.title}`);
          }
          break;
        case 'append':
          if (suggestion.action.content) {
            setContent(prev => prev + '\n' + suggestion.action!.content);
            setSuccessMessage(`Appended suggestion: ${suggestion.title}`);
          }
          break;
        case 'prepend':
          if (suggestion.action.content) {
            setContent(prev => suggestion.action!.content + '\n' + prev);
            setSuccessMessage(`Prepended suggestion: ${suggestion.title}`);
          }
          break;
      }

      // Update suggestion
      setSuggestions(prev =>
        prev.map(s =>
          s.id === suggestion.id ? { ...s, applied: true, appliedAt: new Date() } : s
        )
      );

      if (onSuggestionApplied) {
        onSuggestionApplied(suggestion, content);
      }

      setTimeout(() => setSuccessMessage(null), 3000);
    }
  };

  // Discard suggestion
  const discardSuggestion = (suggestionId: string) => {
    setSuggestions(prev => prev.filter(s => s.id !== suggestionId));
    setSuccessMessage('Suggestion discarded');
    setTimeout(() => setSuccessMessage(null), 2000);
  };

  // Toggle enhancement
  const toggleEnhancement = (enhancementId: string) => {
    setActiveEnhancements(prev => {
      const next = new Set(prev);
      if (next.has(enhancementId)) {
        next.delete(enhancementId);
      } else {
        next.add(enhancementId);
      }
      return next;
    });
  };

  // Clear all
  const clearAll = () => {
    setContent('');
    setAnalysis(null);
    setEnhancedContent('');
    setSummary('');
    setClassification(null);
    setSuggestions([]);
    setError(null);
    setSuccessMessage('Cleared all content and results');
    setTimeout(() => setSuccessMessage(null), 2000);
  };

  // Copy to clipboard
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setSuccessMessage('Copied to clipboard');
    setTimeout(() => setSuccessMessage(null), 2000);
  };

  // Download result
  const downloadResult = () => {
    const result = {
      originalContent: content,
      processedAt: new Date().toISOString(),
      mode: processingMode,
      analysis,
      enhancedContent,
      summary,
      classification,
      suggestions
    };

    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ai-process-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setSuccessMessage('Results downloaded');
    setTimeout(() => setSuccessMessage(null), 2000);
  };

  // Load from file
  const loadFromFile = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json,.txt,.md';
    input.onchange = (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = (event) => {
          setContent(event.target?.result as string);
          setSuccessMessage(`Loaded from ${file.name}`);
          setTimeout(() => setSuccessMessage(null), 2000);
        };
        reader.readAsText(file);
      }
    };
    input.click();
  };

  // Format helpers
  const formatPriority = (priority: string) => {
    const colors = {
      critical: 'bg-red-100 text-red-800',
      high: 'bg-orange-100 text-orange-800',
      medium: 'bg-yellow-100 text-yellow-800',
      low: 'bg-green-100 text-green-800'
    };
    return colors[priority as keyof typeof colors] || colors.medium;
  };

  const getSuggestionIcon = (category: string) => {
    switch (category) {
      case 'code_improvement': return <Code size={16} />;
      case 'security_fix': return <Lock size={16} />;
      case 'performance_optimization': return <Zap size={16} />;
      case 'readability_enhancement': return <Eye size={16} />;
      default: return <HelpCircle size={16} />;
    }
  };

  // Stats
  const stats = getStats();
  const processingStatus = getStatus();

  return (
    <div className={`flex flex-col h-full bg-gray-50 ${className} ${isFullscreen ? 'fixed inset-0 z-50' : ''}`}>
      {/* Header */}
      <div className="border-b border-gray-200 bg-white p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-gradient-to-r from-purple-500 to-blue-500 rounded-lg">
              <Brain className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900">AI Content Processor</h2>
              <p className="text-sm text-gray-600">Analyze, enhance, and summarize content with AI</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-2">
            <button
              onClick={() => setIsFullscreen(!isFullscreen)}
              className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg"
              title={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
            >
              {isFullscreen ? <Minimize2 size={20} /> : <Maximize2 size={20} />}
            </button>
            
            <button
              onClick={clearAll}
              className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg"
              title="Clear all"
            >
              <X size={20} />
            </button>
          </div>
        </div>
      </div>
      
      {/* Main Content */}
      <div className="flex-1 overflow-hidden grid grid-cols-1 lg:grid-cols-3 gap-6 p-6">
        {/* Left Panel - Input and Controls */}
        <div className="lg:col-span-2 space-y-6">
          {/* Mode Selector */}
          <div className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-medium text-gray-900">Processing Mode</h3>
              <div className="flex items-center space-x-2">
                <span className="text-sm text-gray-600">AI Status:</span>
                <span className={`text-sm font-medium ${processingStatus === 'ready'
                  ? 'text-green-600'
                  : processingStatus === 'processing'
                  ? 'text-blue-600'
                  : 'text-yellow-600'
                }`}>
                  {processingStatus === 'ready' ? 'Ready' : 
                   processingStatus === 'processing' ? 'Processing...' : 'Initializing'}
                </span>
              </div>
            </div>
            
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {(['analyze', 'enhance', 'summarize', 'classify', 'translate', 'explain'] as ProcessingMode[]).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setProcessingMode(mode)}
                  className={`p-4 rounded-lg border-2 flex flex-col items-center justify-center space-y-2 ${
                    processingMode === mode
                      ? 'border-blue-500 bg-blue-50'
                      : 'border-gray-200 hover:border-gray-300 hover:bg-gray-50'
                  }`}
                >
                  <div className={`p-2 rounded-full ${
                    processingMode === mode ? 'bg-blue-100' : 'bg-gray-100'
                  }`}>
                    {mode === 'analyze' && <Brain className="w-5 h-5" />}
                    {mode === 'enhance' && <Sparkles className="w-5 h-5" />}
                    {mode === 'summarize' && <FileText className="w-5 h-5" />}
                    {mode === 'classify' && <Filter className="w-5 h-5" />}
                    {mode === 'translate' && <Languages className="w-5 h-5" />}
                    {mode === 'explain' && <HelpCircle className="w-5 h-5" />}
                  </div>
                  <span className="text-sm font-medium capitalize">{mode}</span>
                </button>
              ))}
            </div>
            
            {/* Enhancement Options (only for enhance mode) */}
            {processingMode === 'enhance' && (
              <div className="mt-6 pt-6 border-t border-gray-200">
                <h4 className="font-medium text-gray-900 mb-3">Enhancement Options</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {enhancementOptions.map((option) => (
                    <div
                      key={option.id}
                      className={`p-3 rounded-lg border cursor-pointer ${
                        activeEnhancements.has(option.id)
                          ? 'border-blue-500 bg-blue-50'
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                      onClick={() => toggleEnhancement(option.id)}
                    >
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                          <div className={`p-2 rounded ${
                            activeEnhancements.has(option.id)
                              ? 'bg-blue-100 text-blue-600'
                              : 'bg-gray-100 text-gray-600'
                          }`}>
                            {option.icon}
                          </div>
                          <div>
                            <h5 className="font-medium text-gray-900">{option.label}</h5>
                            <p className="text-xs text-gray-600">{option.description}</p>
                          </div>
                        </div>
                        <div className={`w-5 h-5 rounded border ${
                          activeEnhancements.has(option.id)
                            ? 'bg-blue-500 border-blue-500'
                            : 'border-gray-300'
                        }`}>
                          {activeEnhancements.has(option.id) && (
                            <Check className="w-4 h-4 text-white" />
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
            
            {/* Model Settings (Advanced) */}
            <div className="mt-6 pt-6 border-t border-gray-200">
              <button
                onClick={() => setShowAdvanced(!showAdvanced)}
                className="flex items-center justify-between w-full text-gray-700 hover:text-gray-900"
              >
                <span className="font-medium">Advanced Settings</span>
                <span>{showAdvanced ? '▲' : '▼'}</span>
              </button>
              
              {showAdvanced && (
                <div className="mt-4 space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Temperature: {modelSettings.temperature.toFixed(1)}
                    </label>
                    <input
                      type="range"
                      min="0"
                      max="1"
                      step="0.1"
                      value={modelSettings.temperature}
                      onChange={(e) => setModelSettings(prev => ({
                        ...prev,
                        temperature: parseFloat(e.target.value)
                      }))}
                      className="w-full"
                    />
                    <div className="flex justify-between text-xs text-gray-600 mt-1">
                      <span>More Focused</span>
                      <span>More Creative</span>
                    </div>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Max Tokens: {modelSettings.maxTokens}
                    </label>
                    <input
                      type="range"
                      min="100"
                      max="4000"
                      step="100"
                      value={modelSettings.maxTokens}
                      onChange={(e) => setModelSettings(prev => ({
                        ...prev,
                        maxTokens: parseInt(e.target.value)
                      }))}
                      className="w-full"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Creativity Level
                    </label>
                    <div className="flex space-x-2">
                      {(['conservative', 'balanced', 'creative'] as const).map((level) => (
                        <button
                          key={level}
                          onClick={() => setModelSettings(prev => ({ ...prev, creativity: level }))}
                          className={`px-3 py-1.5 text-sm rounded-md flex-1 ${
                            modelSettings.creativity === level
                              ? 'bg-blue-100 text-blue-700'
                              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                          }`}
                        >
                          {level.charAt(0).toUpperCase() + level.slice(1)}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
          
          {/* Content Input */}
          <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
            <div className="border-b border-gray-200 px-4 py-3 flex items-center justify-between">
              <h3 className="font-medium text-gray-900">Input Content</h3>
              <div className="flex items-center space-x-2">
                <span className="text-sm text-gray-600">
                  {content.length} characters, {content.split(/\s+/).filter(w => w).length} words
                </span>
                <button
                  onClick={loadFromFile}
                  className="p-1.5 text-gray-600 hover:bg-gray-100 rounded"
                  title="Load from file"
                >
                  <Upload size={16} />
                </button>
                <button
                  onClick={clearAll}
                  className="p-1.5 text-gray-600 hover:bg-gray-100 rounded"
                  title="Clear"
                >
                  <X size={16} />
                </button>
              </div>
            </div>
            
            <div className="p-4">
              <textarea
                ref={textareaRef}
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Paste your content here... Or type to get started..."
                className="w-full h-64 font-mono text-sm border border-gray-300 rounded-md p-3 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
              />
              
              <div className="flex items-center justify-between mt-4">
                <div className="flex items-center space-x-2">
                  <button
                    onClick={processContent}
                    disabled={loading || !content.trim()}
                    className="px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-md hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
                  >
                    {loading ? (
                      <>
                        <RotateCw className="w-4 h-4 mr-2 animate-spin" />
                        Processing...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        Process Content
                      </>
                    )}
                  </button>
                  
                  <button
                    onClick={streamContent}
                    disabled={isStreaming || !content.trim()}
                    className="px-4 py-2 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-md hover:from-green-700 hover:to-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
                  >
                    <Zap className="w-4 h-4 mr-2" />
                    Stream AI Response
                  </button>
                </div>
                
                <div className="flex items-center space-x-2">
                  {clipboardItemId && (
                    <button
                      onClick={() => loadClipboardContent(clipboardItemId)}
                      className="px-3 py-1.5 text-sm border border-gray-300 rounded-md hover:bg-gray-50"
                    >
                      Reload from Clipboard
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
          
          {/* Streaming Output */}
          {isStreaming && (
            <div className="bg-white rounded-lg border border-gray-200 p-4">
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-medium text-gray-900">AI Streaming Response</h3>
                <button
                  onClick={() => setIsStreaming(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <X size={16} />
                </button>
              </div>
              <div className="bg-gray-50 rounded p-3 font-mono text-sm whitespace-pre-wrap min-h-[100px]">
                {streamedContent || 'Streaming AI response...'}
              </div>
            </div>
          )}
        </div>
        
        {/* Right Panel - Results and Suggestions */}
        <div className="space-y-6" ref={resultsRef}>
          {/* Stats */}
          <div className="bg-white rounded-lg border border-gray-200 p-4">
            <h3 className="font-medium text-gray-900 mb-3">AI Stats</h3>
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-gray-50 rounded p-3">
                <div className="text-sm text-gray-600">Requests Today</div>
                <div className="text-2xl font-semibold text-gray-900">{stats.requestsToday || 0}</div>
              </div>
              <div className="bg-gray-50 rounded p-3">
                <div className="text-sm text-gray-600">Avg Response Time</div>
                <div className="text-2xl font-semibold text-gray-900">{stats.avgResponseTime || 0}ms</div>
              </div>
              <div className="bg-gray-50 rounded p-3">
                <div className="text-sm text-gray-600">Tokens Used</div>
                <div className="text-2xl font-semibold text-gray-900">{stats.tokensUsed || 0}</div>
              </div>
              <div className="bg-gray-50 rounded p-3">
                <div className="text-sm text-gray-600">Success Rate</div>
                <div className="text-2xl font-semibold text-gray-900">{stats.successRate || 0}%</div>
              </div>
            </div>
          </div>
          
          {/* Results */}
          {(analysis || enhancedContent || summary || classification) && (
            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <div className="border-b border-gray-200 px-4 py-3 flex items-center justify-between">
                <h3 className="font-medium text-gray-900">Results</h3>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={downloadResult}
                    className="p-1.5 text-gray-600 hover:bg-gray-100 rounded"
                    title="Download results"
                  >
                    <Download size={16} />
                  </button>
                  <button
                    onClick={() => setShowSuggestions(!showSuggestions)}
                    className="p-1.5 text-gray-600 hover:bg-gray-100 rounded"
                    title="Toggle suggestions"
                  >
                    {showSuggestions ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
              </div>
              
              <div className="p-4 space-y-4">
                {/* Analysis Results */}
                {analysis && (
                  <div className="space-y-3">
                    <h4 className="font-medium text-gray-900 flex items-center">
                      <BarChart className="w-4 h-4 mr-2" />
                      Analysis Results
                    </h4>
                    <div className="grid grid-cols-2 gap-3">
                      <div className="bg-blue-50 rounded p-3">
                        <div className="text-sm text-blue-700">Complexity</div>
                        <div className="text-lg font-semibold text-blue-900">{analysis.complexity}/100</div>
                        <div className="w-full bg-blue-200 rounded-full h-2 mt-1">
                          <div 
                            className="bg-blue-600 h-2 rounded-full" 
                            style={{ width: `${analysis.complexity}%` }}
                          />
                        </div>
                      </div>
                      <div className="bg-green-50 rounded p-3">
                        <div className="text-sm text-green-700">Quality</div>
                        <div className="text-lg font-semibold text-green-900">{analysis.quality}/100</div>
                        <div className="w-full bg-green-200 rounded-full h-2 mt-1">
                          <div 
                            className="bg-green-600 h-2 rounded-full" 
                            style={{ width: `${analysis.quality}%` }}
                          />
                        </div>
                      </div>
                    </div>
                    
                    {analysis.summary && (
                      <div className="bg-gray-50 rounded p-3">
                        <div className="text-sm font-medium text-gray-700 mb-1">Summary</div>
                        <div className="text-gray-600">{analysis.summary}</div>
                      </div>
                    )}
                    
                    {analysis.potentialIssues.length > 0 && (
                      <div>
                        <div className="text-sm font-medium text-gray-700 mb-1">Potential Issues</div>
                        <ul className="list-disc list-inside text-gray-600 space-y-1">
                          {analysis.potentialIssues.map((issue, index) => (
                            <li key={index}>{issue}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                    
                    {analysis.improvements.length > 0 && (
                      <div>
                        <div className="text-sm font-medium text-gray-700 mb-1">Suggested Improvements</div>
                        <ul className="list-disc list-inside text-gray-600 space-y-1">
                          {analysis.improvements.map((improvement, index) => (
                            <li key={index}>{improvement}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                )}
                
                {/* Enhanced Content */}
                {enhancedContent && (
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Enhanced Content</h4>
                    <div className="bg-gray-50 rounded p-3 font-mono text-sm whitespace-pre-wrap">
                      {enhancedContent}
                    </div>
                    <button
                      onClick={() => copyToClipboard(enhancedContent)}
                      className="mt-2 px-3 py-1.5 text-sm bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200 flex items-center"
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Copy Enhanced Content
                    </button>
                  </div>
                )}
                
                {/* Summary */}
                {summary && (
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Summary</h4>
                    <div className="bg-gray-50 rounded p-3">
                      {summary}
                    </div>
                    <button
                      onClick={() => copyToClipboard(summary)}
                      className="mt-2 px-3 py-1.5 text-sm bg-green-100 text-green-700 rounded-md hover:bg-green-200 flex items-center"
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Copy Summary
                    </button>
                  </div>
                )}
                
                {/* Classification */}
                {classification && (
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Classification</h4>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-gray-600">Primary Type:</span>
                        <span className="font-medium">{classification.primaryType}</span>
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-gray-600">Confidence:</span>
                        <span className="font-medium">{Math.round(classification.confidence * 100)}%</span>
                      </div>
                      {classification.language && (
                        <div className="flex items-center justify-between">
                          <span className="text-gray-600">Language:</span>
                          <span className="font-medium">{classification.language}</span>
                        </div>
                      )}
                      <div className="flex items-center justify-between">
                        <span className="text-gray-600">Sensitive:</span>
                        <span className={`font-medium ${classification.isSensitive ? 'text-red-600' : 'text-green-600'}`}>
                          {classification.isSensitive ? 'Yes' : 'No'}
                        </span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
          
          {/* Suggestions */}
          {showSuggestions && suggestions.length > 0 && (
            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <div className="border-b border-gray-200 px-4 py-3">
                <h3 className="font-medium text-gray-900">AI Suggestions ({suggestions.length})</h3>
              </div>
              
              <div className="p-4 space-y-3 max-h-96 overflow-y-auto">
                {suggestions.map((suggestion) => (
                  <div
                    key={suggestion.id}
                    className={`border rounded-lg p-3 ${suggestion.applied ? 'border-green-200 bg-green-50' : 'border-gray-200'}`}
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center space-x-2">
                        <div className="p-1.5 bg-gray-100 rounded">
                          {getSuggestionIcon(suggestion.type)}
                        </div>
                        <div>
                          <h4 className="font-medium text-gray-900">{suggestion.title}</h4>
                          <span className={`text-xs px-2 py-0.5 rounded-full ${formatPriority(suggestion.priority)}`}>
                            {suggestion.priority}
                          </span>
                        </div>
                      </div>
                      
                      <div className="flex items-center space-x-1">
                        <span className="text-xs text-gray-500">
                          {Math.round(suggestion.confidence * 100)}% confidence
                        </span>
                      </div>
                    </div>
                    
                    <p className="text-sm text-gray-600 mb-3">{suggestion.description}</p>
                    
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-2">
                        {!suggestion.applied && (
                          <button
                            onClick={() => applySuggestion(suggestion)}
                            className="px-3 py-1.5 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700"
                          >
                            Apply Suggestion
                          </button>
                        )}
                        {suggestion.applied && (
                          <span className="text-sm text-green-600 flex items-center">
                            <Check className="w-4 h-4 mr-1" />
                            Applied {suggestion.appliedAt && `at ${suggestion.appliedAt.toLocaleTimeString()}`}
                          </span>
                        )}
                      </div>
                      
                      <button
                        onClick={() => discardSuggestion(suggestion.id)}
                        className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900"
                      >
                        Discard
                      </button>
                    </div>
                  </div>
                ))}
              </div>
              
              <div className="border-t border-gray-200 px-4 py-3 bg-gray-50">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-gray-600">
                    {suggestions.filter(s => s.applied).length} of {suggestions.length} suggestions applied
                  </span>
                  <button
                    onClick={() => {
                      suggestions.forEach(s => {
                        if (s.applyAutomatically && !s.applied) {
                          applySuggestion(s);
                        }
                      });
                    }}
                    className="px-3 py-1.5 text-sm bg-purple-600 text-white rounded-md hover:bg-purple-700"
                  >
                    Apply All Auto-suggestions
                  </button>
                </div>
              </div>
            </div>
          )}
          
          {/* Processing History */}
          {processingHistory.length > 0 && (
            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <div className="border-b border-gray-200 px-4 py-3">
                <h3 className="font-medium text-gray-900">Recent Processing</h3>
              </div>
              
              <div className="p-4 space-y-2 max-h-48 overflow-y-auto">
                {processingHistory.map((item, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between p-2 hover:bg-gray-50 rounded"
                  >
                    <div className="flex items-center space-x-3">
                      <div className="p-1.5 bg-gray-100 rounded">
                        {item.mode === 'analyze' && <Brain className="w-4 h-4" />}
                        {item.mode === 'enhance' && <Sparkles className="w-4 h-4" />}
                        {item.mode === 'summarize' && <FileText className="w-4 h-4" />}
                      </div>
                      <div>
                        <div className="text-sm font-medium text-gray-900 capitalize">{item.mode}</div>
                        <div className="text-xs text-gray-500 truncate max-w-[200px]">
                          {item.content}
                        </div>
                      </div>
                    </div>
                    <div className="text-xs text-gray-500">
                      {item.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
      
      {/* Footer */}
      <div className="border-t border-gray-200 bg-white p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            {error && (
              <div className="flex items-center text-red-600">
                <AlertCircle className="w-4 h-4 mr-1" />
                <span className="text-sm">{error}</span>
              </div>
            )}
            
            {successMessage && (
              <div className="flex items-center text-green-600">
                <Check className="w-4 h-4 mr-1" />
                <span className="text-sm">{successMessage}</span>
              </div>
            )}
            
            {loading && (
              <div className="flex items-center text-blue-600">
                <RotateCw className="w-4 h-4 mr-1 animate-spin" />
                <span className="text-sm">Processing...</span>
              </div>
            )}
          </div>
          
          <div className="flex items-center space-x-2">
            <button
              onClick={() => window.knoux.showSettings('ai')}
              className="inline-flex items-center px-3 py-1.5 text-sm rounded-md bg-gray-100 text-gray-700 hover:bg-gray-200"
            >
              <Settings className="w-4 h-4 mr-1" />
              AI Settings
            </button>
            
            <button
              onClick={downloadResult}
              disabled={!analysis && !enhancedContent && !summary && !classification}
              className="inline-flex items-center px-3 py-1.5 text-sm rounded-md bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Download className="w-4 h-4 mr-1" />
              Export All Results
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
