/**
 * Knoux Clipboard AI - Search Bar Component
 * Advanced search interface with filters, suggestions, and real-time results
 * Generated by Knoux - Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Search,
  Filter,
  X,
  ChevronDown,
  Clock,
  Star,
  Pin,
  FileText,
  Code,
  Lock,
  Zap,
  Save,
  History,
  TrendingUp,
  Calendar,
  Tag
} from 'lucide-react';
import { logger, createLogger } from '../../shared/logger';
import { SearchFilter } from '../../shared/types';
import { ContentCategory, ProgrammingLanguage } from '../../shared/enums';

/**
 * Component props
 */
interface SearchBarProps {
  initialQuery?: string;
  initialFilters?: SearchFilter[];
  onSearch: (query: string, filters: SearchFilter[]) => void;
  onClear?: () => void;
  placeholder?: string;
  showAdvanced?: boolean;
  className?: string;
}

/**
 * Search suggestion
 */
interface SearchSuggestion {
  id: string;
  text: string;
  type: 'recent' | 'saved' | 'suggestion' | 'popular';
  icon?: React.ReactNode;
  count?: number;
}

/**
 * Filter option
 */
interface FilterOption {
  id: string;
  label: string;
  type: SearchFilter['type'];
  value?: any;
  options?: Array<{ label: string; value: any }>;
  icon?: React.ReactNode;
  description?: string;
}

export const SearchBar: React.FC<SearchBarProps> = ({
  initialQuery = '',
  initialFilters = [],
  onSearch,
  onClear,
  placeholder = 'Search clipboard history...',
  showAdvanced = false,
  className = ''
}) => {
  const logger = createLogger({ module: 'SearchBar' });
  
  // State
  const [query, setQuery] = useState(initialQuery);
  const [filters, setFilters] = useState<SearchFilter[]>(initialFilters);
  const [showFilters, setShowFilters] = useState(showAdvanced);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const [suggestions, setSuggestions] = useState<SearchSuggestion[]>([]);
  const [recentSearches, setRecentSearches] = useState<string[]>([]);
  const [savedSearches, setSavedSearches] = useState<SearchSuggestion[]>([]);
  const [activeFilter, setActiveFilter] = useState<string | null>(null);
  
  // Refs
  const searchInputRef = useRef<HTMLInputElement>(null);
  const suggestionsRef = useRef<HTMLDivElement>(null);

  // Filter options
  const filterOptions: FilterOption[] = [
    {
      id: 'contentType',
      label: 'Content Type',
      type: 'contentType',
      icon: <FileText size={16} />,
      options: [
        { label: 'Code', value: ContentCategory.CODE },
        { label: 'Text', value: ContentCategory.TEXT },
        { label: 'Data', value: ContentCategory.DATA },
        { label: 'Document', value: ContentCategory.DOCUMENT },
        { label: 'Media', value: ContentCategory.MEDIA },
        { label: 'Configuration', value: ContentCategory.CONFIG },
        { label: 'Logs', value: ContentCategory.LOG }
      ]
    },
    {
      id: 'language',
      label: 'Programming Language',
      type: 'contentType',
      icon: <Code size={16} />,
      options: [
        { label: 'JavaScript', value: ProgrammingLanguage.JAVASCRIPT },
        { label: 'TypeScript', value: ProgrammingLanguage.TYPESCRIPT },
        { label: 'Python', value: ProgrammingLanguage.PYTHON },
        { label: 'HTML', value: ProgrammingLanguage.HTML },
        { label: 'CSS', value: ProgrammingLanguage.CSS },
        { label: 'JSON', value: ProgrammingLanguage.JSON },
        { label: 'SQL', value: ProgrammingLanguage.SQL },
        { label: 'PowerShell', value: ProgrammingLanguage.POWERSHELL },
        { label: 'Bash', value: ProgrammingLanguage.BASH }
      ]
    },
    {
      id: 'sensitive',
      label: 'Sensitive Content',
      type: 'hasSensitive',
      icon: <Lock size={16} />,
      options: [
        { label: 'Show Sensitive', value: true },
        { label: 'Hide Sensitive', value: false }
      ]
    },
    {
      id: 'dateRange',
      label: 'Date Range',
      type: 'dateRange',
      icon: <Calendar size={16} />,
      description: 'Filter by when content was copied'
    },
    {
      id: 'size',
      label: 'Size Range',
      type: 'minSize',
      icon: <Zap size={16} />,
      description: 'Filter by content size'
    },
    {
      id: 'tags',
      label: 'Tags',
      type: 'tags',
      icon: <Tag size={16} />,
      description: 'Filter by tags'
    },
    {
      id: 'favorites',
      label: 'Favorites Only',
      type: 'hasSensitive', // Reusing type for simplicity
      icon: <Star size={16} />,
      value: 'favorites'
    },
    {
      id: 'pinned',
      label: 'Pinned Only',
      type: 'hasSensitive', // Reusing type for simplicity
      icon: <Pin size={16} />,
      value: 'pinned'
    }
  ];

  // Initialize
  useEffect(() => {
    loadRecentSearches();
    loadSavedSearches();
    generateSuggestions();
  }, []);

  // Handle clicks outside suggestions
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        suggestionsRef.current &&
        !suggestionsRef.current.contains(event.target as Node) &&
        searchInputRef.current &&
        !searchInputRef.current.contains(event.target as Node)
      ) {
        setShowSuggestions(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  // Update suggestions based on query
  useEffect(() => {
    if (query.trim()) {
      generateSuggestions();
    }
  }, [query]);

  // Load recent searches from storage
  const loadRecentSearches = async () => {
    try {
      // In production, load from localStorage or database
      const stored = localStorage.getItem('knoux_recent_searches');
      if (stored) {
        setRecentSearches(JSON.parse(stored));
      }
    } catch (error) {
      logger.error('Failed to load recent searches', error as Error);
    }
  };

  // Load saved searches
  const loadSavedSearches = () => {
    // Mock data for demonstration
    const saved: SearchSuggestion[] = [
      {
        id: 'saved_1',
        text: 'error logs',
        type: 'saved',
        icon: <FileText size={14} />,
        count: 24
      },
      {
        id: 'saved_2',
        text: 'api keys',
        type: 'saved',
        icon: <Lock size={14} />,
        count: 8
      },
      {
        id: 'saved_3',
        text: 'javascript functions',
        type: 'saved',
        icon: <Code size={14} />,
        count: 156
      }
    ];
    setSavedSearches(saved);
  };

  // Generate suggestions based on current query
  const generateSuggestions = () => {
    const newSuggestions: SearchSuggestion[] = [];

    // Recent searches
    recentSearches.slice(0, 3).forEach((search, index) => {
      newSuggestions.push({
        id: `recent_${index}`,
        text: search,
        type: 'recent',
        icon: <History size={14} />
      });
    });

    // Saved searches
    savedSearches.slice(0, 2).forEach(saved => {
      newSuggestions.push(saved);
    });

    // Popular searches (mock data)
    if (!query.trim()) {
      newSuggestions.push(
        {
          id: 'pop_1',
          text: 'error handling',
          type: 'popular',
          icon: <TrendingUp size={14} />,
          count: 89
        },
        {
          id: 'pop_2',
          text: 'configuration',
          type: 'popular',
          icon: <FileText size={14} />,
          count: 42
        },
        {
          id: 'pop_3',
          text: 'authentication',
          type: 'popular',
          icon: <Lock size={14} />,
          count: 67
        }
      );
    }

    // Query-based suggestions
    if (query.trim().length > 2) {
      const queryLower = query.toLowerCase();
      const possibleSuggestions = [
        `${queryLower} function`,
        `${queryLower} example`,
        `${queryLower} error`,
        `${queryLower} configuration`,
        `${queryLower} setup`
      ];

      possibleSuggestions.forEach((suggestion, index) => {
        newSuggestions.push({
          id: `suggestion_${index}`,
          text: suggestion,
          type: 'suggestion',
          icon: <Search size={14} />
        });
      });
    }

    setSuggestions(newSuggestions);
  };

  // Handle search
  const handleSearch = useCallback(async () => {
    if (!query.trim() && filters.length === 0) {
      return;
    }

    setIsSearching(true);
    setShowSuggestions(false);

    try {
      logger.debug('Executing search', { query, filterCount: filters.length });

      // Save to recent searches
      if (query.trim()) {
        const updatedRecent = [query, ...recentSearches.filter(s => s !== query)].slice(0, 10);
        setRecentSearches(updatedRecent);
        localStorage.setItem('knoux_recent_searches', JSON.stringify(updatedRecent));
      }

      // Execute search callback
      onSearch(query, filters);

    } catch (error) {
      logger.error('Search failed', error as Error);
    } finally {
      setIsSearching(false);
    }
  }, [query, filters, recentSearches, onSearch]);

  // Handle clear
  const handleClear = () => {
    setQuery('');
    setFilters([]);
    setShowSuggestions(false);
    
    if (onClear) {
      onClear();
    }
    
    searchInputRef.current?.focus();
  };

  // Handle filter change
  const handleFilterChange = (filter: SearchFilter) => {
    setFilters(prev => {
      const existingIndex = prev.findIndex(f => f.type === filter.type);
      
      if (existingIndex >= 0) {
        // Update existing filter
        const updated = [...prev];
        updated[existingIndex] = filter;
        
        // Remove if value is empty/undefined
        if (filter.value === undefined || filter.value === '') {
          updated.splice(existingIndex, 1);
          return updated;
        }
        
        return updated;
      } else {
        // Add new filter
        return [...prev, filter];
      }
    });
    
    setActiveFilter(null);
  };

  // Handle filter removal
  const handleFilterRemove = (filterType: string) => {
    setFilters(prev => prev.filter(f => f.type !== filterType));
  };

  // Handle suggestion click
  const handleSuggestionClick = (suggestion: SearchSuggestion) => {
    setQuery(suggestion.text);
    setShowSuggestions(false);
    searchInputRef.current?.focus();
    
    // Auto-search for certain types
    if (suggestion.type === 'recent' || suggestion.type === 'saved') {
      setTimeout(() => handleSearch(), 100);
    }
  };

  // Save current search
  const handleSaveSearch = () => {
    if (!query.trim() && filters.length === 0) {
      return;
    }

    const searchName = prompt('Name this search:', query || 'Custom Search');
    if (!searchName) return;

    const newSavedSearch: SearchSuggestion = {
      id: `saved_${Date.now()}`,
      text: searchName,
      type: 'saved',
      icon: <Star size={14} />
    };

    setSavedSearches(prev => [newSavedSearch, ...prev]);
    
    logger.info('Search saved', { name: searchName });
  };

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Focus search on Ctrl/Cmd + K
      if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
        event.preventDefault();
        searchInputRef.current?.focus();
      }
      
      // Search on Enter
      if (event.key === 'Enter' && document.activeElement === searchInputRef.current) {
        handleSearch();
      }
      
      // Clear on Escape
      if (event.key === 'Escape' && document.activeElement === searchInputRef.current) {
        handleClear();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [handleSearch]);

  // Get filter display value
  const getFilterDisplayValue = (filter: SearchFilter): string => {
    switch (filter.type) {
      case 'contentType':
        return filter.value || '';
      case 'hasSensitive':
        return filter.value ? 'Sensitive' : 'Not Sensitive';
      case 'dateRange':
        return `${filter.startDate?.toLocaleDateString()} - ${filter.endDate?.toLocaleDateString()}`;
      case 'minSize':
        return `> ${filter.value} bytes`;
      case 'maxSize':
        return `< ${filter.value} bytes`;
      case 'tags':
        return Array.isArray(filter.value) ? filter.value.join(', ') : String(filter.value);
      default:
        return String(filter.value);
    }
  };

  // Get filter icon
  const getFilterIcon = (filterType: string) => {
    const option = filterOptions.find(f => f.id === filterType);
    return option?.icon || <Filter size={14} />;
  };

  // Render filter input based on type
  const renderFilterInput = (filterOption: FilterOption) => {
    switch (filterOption.type) {
      case 'contentType':
        return (
          <div className="space-y-2">
            <div className="grid grid-cols-2 gap-2">
              {filterOption.options?.map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleFilterChange({
                    type: filterOption.type,
                    value: option.value
                  })}
                  className="px-3 py-2 text-sm border rounded-lg hover:bg-gray-50 text-left"
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>
        );

      case 'hasSensitive':
        return (
          <div className="space-y-2">
            {filterOption.options?.map((option) => (
              <button
                key={option.value.toString()}
                onClick={() => handleFilterChange({
                  type: filterOption.type,
                  value: option.value
                })}
                className={`w-full px-3 py-2 text-sm rounded-lg ${
                  filters.find(f => f.type === filterOption.type && f.value === option.value)
                    ? 'bg-blue-100 text-blue-700'
                    : 'hover:bg-gray-50'
                }`}
              >
                {option.label}
              </button>
            ))}
          </div>
        );

      case 'dateRange':
        const today = new Date();
        const yesterday = new Date(today);
        yesterday.setDate(yesterday.getDate() - 1);
        const lastWeek = new Date(today);
        lastWeek.setDate(lastWeek.getDate() - 7);
        const lastMonth = new Date(today);
        lastMonth.setMonth(lastMonth.getMonth() - 1);

        const dateRanges = [
          { label: 'Today', start: today, end: today },
          { label: 'Yesterday', start: yesterday, end: yesterday },
          { label: 'Last 7 days', start: lastWeek, end: today },
          { label: 'Last 30 days', start: lastMonth, end: today }
        ];

        return (
          <div className="space-y-2">
            {dateRanges.map((range) => (
              <button
                key={range.label}
                onClick={() => handleFilterChange({
                  type: 'dateRange',
                  startDate: range.start,
                  endDate: range.end
                })}
                className="w-full px-3 py-2 text-sm hover:bg-gray-50 rounded-lg text-left"
              >
                {range.label}
              </button>
            ))}
            <div className="pt-2 border-t">
              <p className="text-xs text-gray-500 mb-2">Custom range:</p>
              <div className="grid grid-cols-2 gap-2">
                <input
                  type="date"
                  className="px-2 py-1 text-sm border rounded"
                  onChange={(e) => {
                    const startDate = e.target.value ? new Date(e.target.value) : undefined;
                    const currentFilter = filters.find(f => f.type === 'dateRange');
                    handleFilterChange({
                      type: 'dateRange',
                      startDate: startDate,
                      endDate: currentFilter?.endDate
                    });
                  }}
                />
                <input
                  type="date"
                  className="px-2 py-1 text-sm border rounded"
                  onChange={(e) => {
                    const endDate = e.target.value ? new Date(e.target.value) : undefined;
                    const currentFilter = filters.find(f => f.type === 'dateRange');
                    handleFilterChange({
                      type: 'dateRange',
                      startDate: currentFilter?.startDate,
                      endDate: endDate
                    });
                  }}
                />
              </div>
            </div>
          </div>
        );

      case 'minSize':
      case 'maxSize':
        const sizeOptions = [
          { label: 'Small (< 1KB)', value: 1024 },
          { label: 'Medium (< 10KB)', value: 10240 },
          { label: 'Large (< 100KB)', value: 102400 },
          { label: 'Huge (< 1MB)', value: 1048576 }
        ];

        return (
          <div className="space-y-2">
            {sizeOptions.map((option) => (
              <button
                key={option.value}
                onClick={() => handleFilterChange({
                  type: filterOption.type,
                  value: option.value
                })}
                className="w-full px-3 py-2 text-sm hover:bg-gray-50 rounded-lg text-left"
              >
                {option.label}
              </button>
            ))}
            <div className="pt-2 border-t">
              <p className="text-xs text-gray-500 mb-2">Custom size (bytes):</p>
              <input
                type="number"
                className="w-full px-2 py-1 text-sm border rounded"
                placeholder="Enter size in bytes"
                onChange={(e) => {
                  const value = parseInt(e.target.value);
                  if (!isNaN(value)) {
                    handleFilterChange({
                      type: filterOption.type,
                      value: value
                    });
                  }
                }}
              />
            </div>
          </div>
        );

      case 'tags':
        // Mock tags - in production, these would come from the database
        const mockTags = ['work', 'personal', 'code', 'config', 'error', 'api', 'security', 'temp'];
        
        return (
          <div className="space-y-2">
            <div className="flex flex-wrap gap-1">
              {mockTags.map((tag) => (
                <button
                  key={tag}
                  onClick={() => {
                    const currentFilter = filters.find(f => f.type === 'tags');
                    const currentTags = currentFilter?.value || [];
                    const newTags = Array.isArray(currentTags) 
                      ? [...currentTags, tag]
                      : [tag];
                    
                    handleFilterChange({
                      type: 'tags',
                      value: Array.from(new Set(newTags))
                    });
                  }}
                  className="px-2 py-1 text-xs bg-gray-100 rounded hover:bg-gray-200"
                >
                  {tag}
                </button>
              ))}
            </div>
            <div className="pt-2 border-t">
              <input
                type="text"
                className="w-full px-2 py-1 text-sm border rounded"
                placeholder="Add custom tag..."
                onKeyPress={(e) => {
                  if (e.key === 'Enter') {
                    const input = e.target as HTMLInputElement;
                    if (input.value.trim()) {
                      const currentFilter = filters.find(f => f.type === 'tags');
                      const currentTags = currentFilter?.value || [];
                      const newTags = Array.isArray(currentTags) 
                        ? [...currentTags, input.value.trim()]
                        : [input.value.trim()];
                      
                      handleFilterChange({
                        type: 'tags',
                        value: Array.from(new Set(newTags))
                      });
                      
                      input.value = '';
                    }
                  }
                }}
              />
            </div>
          </div>
        );

      default:
        return (
          <input
            type="text"
            className="w-full px-3 py-2 text-sm border rounded"
            placeholder={`Enter ${filterOption.label.toLowerCase()}...`}
            onChange={(e) => handleFilterChange({
              type: filterOption.type,
              value: e.target.value
            })}
          />
        );
    }
  };

  return (
    <div className={`relative ${className}`}>
      {/* Search Bar */}
      <div className="relative">
        <div className="flex items-center bg-white border border-gray-300 rounded-lg shadow-sm hover:border-gray-400 focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-200 transition-all duration-200">
          {/* Search Icon */}
          <div className="pl-3">
            <Search className="w-5 h-5 text-gray-400" />
          </div>

          {/* Search Input */}
          <input
            ref={searchInputRef}
            type="text"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              if (e.target.value.trim()) {
                setShowSuggestions(true);
              }
            }}
            onFocus={() => setShowSuggestions(true)}
            placeholder={placeholder}
            className="flex-1 px-3 py-3 text-gray-900 bg-transparent border-none focus:outline-none focus:ring-0 placeholder-gray-500"
            aria-label="Search clipboard history"
          />

          {/* Search Actions */}
          <div className="flex items-center pr-2 space-x-1">
            {/* Clear Button */}
            {(query.trim() || filters.length > 0) && (
              <button
                onClick={handleClear}
                className="p-1.5 text-gray-400 hover:text-gray-600 rounded-full hover:bg-gray-100"
                aria-label="Clear search"
                title="Clear search"
              >
                <X className="w-4 h-4" />
              </button>
            )}

            {/* Filter Toggle */}
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`p-1.5 rounded-full ${
                filters.length > 0
                  ? 'bg-blue-100 text-blue-600'
                  : 'text-gray-400 hover:text-gray-600 hover:bg-gray-100'
              }`}
              aria-label="Toggle filters"
              title="Toggle filters"
            >
              <Filter className="w-4 h-4" />
              {filters.length > 0 && (
                <span className="absolute -top-1 -right-1 w-4 h-4 text-xs bg-blue-600 text-white rounded-full flex items-center justify-center">
                  {filters.length}
                </span>
              )}
            </button>

            {/* Search Button */}
            <button
              onClick={handleSearch}
              disabled={isSearching || (!query.trim() && filters.length === 0)}
              className={`px-4 py-1.5 ml-1 rounded-md ${
                isSearching
                  ? 'bg-gray-100 text-gray-400'
                  : 'bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700'
              } disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-200`}
              aria-label="Search"
            >
              {isSearching ? 'Searching...' : 'Search'}
            </button>
          </div>
        </div>

        {/* Keyboard Shortcut Hint */}
        <div className="absolute right-2 top-1/2 transform -translate-y-1/2 hidden md:block">
          <kbd className="px-2 py-1 text-xs font-mono text-gray-500 bg-gray-100 rounded border">
            ⌘K
          </kbd>
        </div>
      </div>

      {/* Active Filters */}
      {filters.length > 0 && (
        <div className="flex flex-wrap gap-2 mt-3">
          {filters.map((filter, index) => (
            <div
              key={`${filter.type}_${index}`}
              className="inline-flex items-center px-3 py-1.5 bg-blue-50 text-blue-800 rounded-full text-sm"
            >
              <span className="mr-1">{getFilterIcon(filter.type)}</span>
              <span className="font-medium mr-2">
                {filterOptions.find(f => f.id === filter.type)?.label || filter.type}:
              </span>
              <span>{getFilterDisplayValue(filter)}</span>
              <button
                onClick={() => handleFilterRemove(filter.type)}
                className="ml-2 text-blue-600 hover:text-blue-800"
                aria-label={`Remove ${filter.type} filter`}
              >
                <X className="w-3 h-3" />
              </button>
            </div>
          ))}
          
          {/* Clear All Filters Button */}
          {filters.length > 1 && (
            <button
              onClick={() => setFilters([])}
              className="px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-full"
            >
              Clear all
            </button>
          )}
        </div>
      )}

      {/* Filter Panel */}
      {showFilters && (
        <div className="absolute left-0 right-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg z-50">
          <div className="p-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-medium text-gray-900">Advanced Filters</h3>
              <button
                onClick={() => setShowFilters(false)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {filterOptions.map((option) => (
                <div
                  key={option.id}
                  className={`border rounded-lg p-3 ${
                    activeFilter === option.id
                      ? 'border-blue-500 bg-blue-50'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <button
                    onClick={() => setActiveFilter(
                      activeFilter === option.id ? null : option.id
                    )}
                    className="flex items-center justify-between w-full text-left"
                  >
                    <div className="flex items-center space-x-2">
                      <span className="text-gray-600">{option.icon}</span>
                      <span className="font-medium text-gray-900">{option.label}</span>
                    </div>
                    <ChevronDown className={`w-4 h-4 transition-transform ${
                      activeFilter === option.id ? 'transform rotate-180' : ''
                    }`} />
                  </button>

                  {option.description && (
                    <p className="text-xs text-gray-500 mt-1">{option.description}</p>
                  )}

                  {activeFilter === option.id && (
                    <div className="mt-3 pt-3 border-t">
                      {renderFilterInput(option)}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="flex items-center justify-between mt-6 pt-4 border-t">
              <div className="text-sm text-gray-600">
                {filters.length} filter{filters.length !== 1 ? 's' : ''} active
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => setFilters([])}
                  className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50"
                >
                  Reset Filters
                </button>
                <button
                  onClick={handleSaveSearch}
                  className="px-4 py-2 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg hover:from-green-700 hover:to-emerald-700 flex items-center"
                >
                  <Save className="w-4 h-4 mr-2" />
                  Save Search
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Search Suggestions */}
      {showSuggestions && suggestions.length > 0 && (
        <div
          ref={suggestionsRef}
          className="absolute left-0 right-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg z-40 max-h-96 overflow-y-auto"
        >
          <div className="p-2">
            {/* Recent Searches */}
            {suggestions.filter(s => s.type === 'recent').length > 0 && (
              <div className="mb-3">
                <div className="flex items-center px-3 py-2 text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <History className="w-3 h-3 mr-2" />
                  Recent Searches
                </div>
                {suggestions
                  .filter(s => s.type === 'recent')
                  .map((suggestion) => (
                    <button
                      key={suggestion.id}
                      onClick={() => handleSuggestionClick(suggestion)}
                      className="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 rounded-lg"
                    >
                      <div className="flex items-center">
                        <Clock className="w-4 h-4 mr-3 text-gray-400" />
                        <span>{suggestion.text}</span>
                      </div>
                    </button>
                  ))}
              </div>
            )}

            {/* Saved Searches */}
            {suggestions.filter(s => s.type === 'saved').length > 0 && (
              <div className="mb-3">
                <div className="flex items-center px-3 py-2 text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <Star className="w-3 h-3 mr-2" />
                  Saved Searches
                </div>
                {suggestions
                  .filter(s => s.type === 'saved')
                  .map((suggestion) => (
                    <button
                      key={suggestion.id}
                      onClick={() => handleSuggestionClick(suggestion)}
                      className="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 rounded-lg"
                    >
                      <div className="flex items-center">
                        <Star className="w-4 h-4 mr-3 text-yellow-500" />
                        <span>{suggestion.text}</span>
                      </div>
                      {suggestion.count && (
                        <span className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">
                          {suggestion.count} results
                        </span>
                      )}
                    </button>
                  ))}
              </div>
            )}

            {/* Popular Searches */}
            {suggestions.filter(s => s.type === 'popular').length > 0 && (
              <div className="mb-3">
                <div className="flex items-center px-3 py-2 text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <TrendingUp className="w-3 h-3 mr-2" />
                  Popular Now
                </div>
                {suggestions
                  .filter(s => s.type === 'popular')
                  .map((suggestion) => (
                    <button
                      key={suggestion.id}
                      onClick={() => handleSuggestionClick(suggestion)}
                      className="flex items-center justify-between w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 rounded-lg"
                    >
                      <div className="flex items-center">
                        <TrendingUp className="w-4 h-4 mr-3 text-green-500" />
                        <span>{suggestion.text}</span>
                      </div>
                      {suggestion.count && (
                        <span className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">
                          {suggestion.count}
                        </span>
                      )}
                    </button>
                  ))}
              </div>
            )}

            {/* Query Suggestions */}
            {suggestions.filter(s => s.type === 'suggestion').length > 0 && (
              <div>
                <div className="flex items-center px-3 py-2 text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <Search className="w-3 h-3 mr-2" />
                  Suggestions
                </div>
                {suggestions
                  .filter(s => s.type === 'suggestion')
                  .map((suggestion) => (
                    <button
                      key={suggestion.id}
                      onClick={() => handleSuggestionClick(suggestion)}
                      className="flex items-center w-full px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 rounded-lg"
                    >
                      <Search className="w-4 h-4 mr-3 text-gray-400" />
                      <span>"{suggestion.text}"</span>
                    </button>
                  ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t px-3 py-2 bg-gray-50">
            <div className="flex items-center justify-between text-xs text-gray-500">
              <span>Press Enter to search • Esc to clear</span>
              <span>⌘K to focus search</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
