/**
 * Knoux Clipboard AI - Settings Panel Component
 * Comprehensive settings panel for customizing all application preferences
 * Generated by Knoux — Abu Retaj
 * Clipboard Intelligence • Desktop Precision • Premium Engineering
 */

import React, { useState, useEffect, useCallback } from 'react';
import {
  Settings,
  Save,
  RotateCw,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Bell,
  Palette,
  Globe,
  Zap,
  Shield,
  Database,
  Cpu,
  Network,
  Keyboard,
  User,
  Moon,
  Sun,
  Monitor,
  LogOut,
  Trash2,
  Download,
  Upload,
  HelpCircle,
  Check,
  X,
  AlertTriangle,
  RefreshCw
} from 'lucide-react';
import { llog } from '../../shared/localized-logger';
import { 
  UserPreferences,
  AppStatistics,
  SystemInfo
} from '../../shared/types';
import { 
  UITheme,
  UILanguage,
  DetectionMode,
  StorageType,
  AIModelType
} from '../../shared/enums';

/**
 * Component props
 */
interface SettingsPanelProps {
  initialSettings?: Partial<UserPreferences>;
  onSettingsChange?: (settings: UserPreferences) => void;
  onSave?: (settings: UserPreferences) => void;
  onReset?: () => void;
  className?: string;
}

/**
 * Settings section
 */
type SettingsSection = 
  | 'general' 
  | 'clipboard' 
  | 'ai' 
  | 'appearance' 
  | 'security' 
  | 'performance' 
  | 'storage' 
  | 'backup' 
  | 'about'
  | 'advanced';

/**
 * Language option
 */
interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

/**
 * Theme option
 */
interface ThemeOption {
  id: string;
  name: string;
  icon: React.ReactNode;
  colors: {
    primary: string;
    background: string;
    text: string;
  };
}

export const SettingsPanel: React.FC<SettingsPanelProps> = ({
  initialSettings = {},
  onSettingsChange,
  onSave,
  onReset,
  className = ''
}) => {
  const logger = createLogger({ module: 'SettingsPanel' });
  
  // Default settings
  const defaultSettings: UserPreferences = {
    // General
    language: 'en',
    theme: 'dark',
    fontSize: 14,
    animations: true,
    tooltips: true,
    notifications: true,
    
    // Clipboard
    autoStart: true,
    pollInterval: 500,
    maxHistoryItems: 1000,
    captureImages: false,
    captureHtml: true,
    captureRtf: true,
    autoClearSensitive: true,
    autoClearMinutes: 5,
    
    // AI
    aiEnabled: true,
    defaultModel: 'llama-2-7b-chat',
    autoEnhance: false,
    autoSummarize: false,
    autoClassify: true,
    confidenceThreshold: 0.7,
    useCloudModels: false,
    
    // Security
    encryptSensitive: true,
    requirePassword: false,
    autoLockMinutes: 30,
    clearClipboardOnExit: false,
    anonymizeData: true,
    
    // Performance
    cacheEnabled: true,
    cacheSizeMB: 100,
    workerCount: 4,
    compressionLevel: 6,
    
    // UI
    showLineNumbers: true,
    wordWrap: true,
    tabSize: 2,
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    sidebarPosition: 'left',
    defaultView: 'list'
  };
  
  // State
  const [settings, setSettings] = useState<UserPreferences>({
    ...defaultSettings,
    ...initialSettings
  });
  const [activeSection, setActiveSection] = useState<SettingsSection>('general');
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [systemInfo, setSystemInfo] = useState<SystemInfo | null>(null);
  const [stats, setStats] = useState<AppStatistics | null>(null);
  const [exportFormat, setExportFormat] = useState<'json' | 'csv'>('json');
  const [importFile, setImportFile] = useState<File | null>(null);
  const [backupProgress, setBackupProgress] = useState(0);
  const [restoreProgress, setRestoreProgress] = useState(0);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  
  // Language options
  const languageOptions: LanguageOption[] = [
    { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
    { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
    { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
    { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
    { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
    { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' }
  ];
  
  // Theme options
  const themeOptions: ThemeOption[] = [
    {
      id: 'light',
      name: 'Light',
      icon: <Sun size={20} />,
      colors: {
        primary: '#3b82f6',
        background: '#ffffff',
        text: '#1f2937'
      }
    },
    {
      id: 'dark',
      name: 'Dark',
      icon: <Moon size={20} />,
      colors: {
        primary: '#60a5fa',
        background: '#111827',
        text: '#f3f4f6'
      }
    },
    {
      id: 'auto',
      name: 'Auto',
      icon: <Monitor size={20} />,
      colors: {
        primary: '#8b5cf6',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        text: '#ffffff'
      }
    }
  ];
  
  // AI models
  const aiModels = [
    { id: 'llama-2-7b-chat', name: 'Llama 2 7B', type: AIModelType.LOCAL_LLAMA, size: '7B', local: true },
    { id: 'llama-2-13b-chat', name: 'Llama 2 13B', type: AIModelType.LOCAL_LLAMA, size: '13B', local: true },
    { id: 'gpt-4', name: 'GPT-4', type: AIModelType.CLOUD_OPENAI, size: 'Unknown', local: false },
    { id: 'claude-3', name: 'Claude 3', type: AIModelType.CLOUD_ANTHROPIC, size: 'Unknown', local: false },
    { id: 'gemini-pro', name: 'Gemini Pro', type: AIModelType.CLOUD_GOOGLE, size: 'Unknown', local: false }
  ];
  
  // Storage types
  const storageTypes = [
    { id: StorageType.LOCAL_SQLITE, name: 'Local SQLite', description: 'Fast, reliable local storage' },
    { id: StorageType.INDEXED_DB, name: 'IndexedDB', description: 'Browser-based storage' },
    { id: StorageType.LOCAL_STORAGE, name: 'Local Storage', description: 'Simple key-value storage' },
    { id: StorageType.MEMORY, name: 'Memory', description: 'Fast but temporary' }
  ];
  
  // Load system info and stats
  useEffect(() => {
    loadSystemInfo();
    loadStats();
  }, []);
  
  // Load system info
  const loadSystemInfo = async () => {
    try {
      const response = await window.knoux.getSystemInfo();
      if (response.success) {
        setSystemInfo(response.data);
      }
    } catch (error) {
      llog.error('Failed to load system info', error as Error);
    }
  };
  
  // Load statistics
  const loadStats = async () => {
    try {
      const response = await window.knoux.getStatistics();
      if (response.success) {
        setStats(response.data);
      }
    } catch (error) {
      llog.error('Failed to load statistics', error as Error);
    }
  };
  
  // Handle setting change
  const handleSettingChange = useCallback((key: keyof UserPreferences, value: any) => {
    setSettings(prev => {
      const newSettings = { ...prev, [key]: value };
      setHasUnsavedChanges(true);
      
      if (onSettingsChange) {
        onSettingsChange(newSettings);
      }
      
      return newSettings;
    });
  }, [onSettingsChange]);
  
  // Save settings
  const saveSettings = async () => {
    setIsSaving(true);
    
    try {
      llog.info('Saving settings', settings);
      
      // In production, this would save to storage via IPC
      await new Promise(resolve => setTimeout(resolve, 500)); // Simulated delay
      
      setHasUnsavedChanges(false);
      
      if (onSave) {
        onSave(settings);
      }
      
      llog.info('Settings saved successfully');
    } catch (error) {
      llog.error('Failed to save settings', error as Error);
    } finally {
      setIsSaving(false);
    }
  };
  
  // Reset to defaults
  const resetToDefaults = () => {
    setSettings(defaultSettings);
    setHasUnsavedChanges(true);
    setShowResetConfirm(false);
    
    if (onReset) {
      onReset();
    }
  };
  
  // Export settings
  const exportSettings = () => {
    const exportData = {
      settings,
      exportedAt: new Date().toISOString(),
      version: '1.0.0'
    };
    
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `knoux-settings-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  // Import settings
  const importSettings = (file: File) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const imported = JSON.parse(event.target?.result as string);
        
        if (imported.settings) {
          setSettings({
            ...defaultSettings,
            ...imported.settings
          });
          setHasUnsavedChanges(true);
          llog.info('Settings imported successfully');
        }
      } catch (error) {
        llog.error('Failed to import settings', error as Error);
      }
    };
    reader.readAsText(file);
  };
  
  // Create backup
  const createBackup = async () => {
    setBackupProgress(0);
    
    // Simulate backup progress
    const interval = setInterval(() => {
      setBackupProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + 10;
      });
    }, 100);
    
    try {
      const response = await window.knoux.createBackup();
      if (response.success) {
        llog.info('Backup created successfully');
      }
    } catch (error) {
      llog.error('Failed to create backup', error as Error);
    } finally {
      setTimeout(() => setBackupProgress(0), 1000);
    }
  };
  
  // Restore backup
  const restoreBackup = async () => {
    setRestoreProgress(0);
    
    // Simulate restore progress
    const interval = setInterval(() => {
      setRestoreProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + 10;
      });
    }, 100);
    
    try {
      const response = await window.knoux.restoreBackup();
      if (response.success) {
        llog.info('Backup restored successfully');
      }
    } catch (error) {
      llog.error('Failed to restore backup', error as Error);
    } finally {
      setTimeout(() => setRestoreProgress(0), 1000);
    }
  };
  
  // Clear all data
  const clearAllData = async () => {
    if (window.confirm('Are you sure you want to clear all data? This action cannot be undone.')) {
      try {
        await window.knoux.clearAllData();
        llog.info('All data cleared');
      } catch (error) {
        llog.error('Failed to clear data', error as Error);
      }
    }
  };
  
  // Format file size
  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };
  
  // Format time
  const formatTime = (ms: number) => {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    
    if (hours > 0) return `${hours}h ${minutes % 60}m`;
    if (minutes > 0) return `${minutes}m ${seconds % 60}s`;
    return `${seconds}s`;
  };
  
  return (
    <div className={`flex flex-col h-full bg-gray-50 ${className}`}>
      {/* Header */}
      <div className="border-b border-gray-200 bg-white p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="p-3 bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl">
              <Settings className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
              <p className="text-gray-600">Customize your Knoux Clipboard AI experience</p>
            </div>
          </div>
          
          <div className="flex items-center space-x-3">
            {hasUnsavedChanges && (
              <span className="text-sm text-yellow-600 flex items-center">
                <AlertTriangle className="w-4 h-4 mr-1" />
                Unsaved changes
              </span>
            )}
            
            <button
              onClick={() => setShowResetConfirm(true)}
              className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 flex items-center"
            >
              <RotateCw className="w-4 h-4 mr-2" />
              Reset
            </button>
            
            <button
              onClick={saveSettings}
              disabled={isSaving || !hasUnsavedChanges}
              className="px-4 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
            >
              {isSaving ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  Save Changes
                </>
              )}
            </button>
          </div>
        </div>
      </div>
      
      {/* Main Content */}
      <div className="flex-1 overflow-hidden grid grid-cols-1 lg:grid-cols-4">
        {/* Sidebar */}
        <div className="lg:col-span-1 border-r border-gray-200 bg-white">
          <nav className="p-4 space-y-1">
            {([
              { id: 'general' as SettingsSection, label: 'General', icon: <Settings size={20} /> },
              { id: 'clipboard' as SettingsSection, label: 'Clipboard', icon: <Database size={20} /> },
              { id: 'ai' as SettingsSection, label: 'AI', icon: <Cpu size={20} /> },
              { id: 'appearance' as SettingsSection, label: 'Appearance', icon: <Palette size={20} /> },
              { id: 'security' as SettingsSection, label: 'Security', icon: <Shield size={20} /> },
              { id: 'performance' as SettingsSection, label: 'Performance', icon: <Zap size={20} /> },
              { id: 'storage' as SettingsSection, label: 'Storage', icon: <Database size={20} /> },
              { id: 'backup' as SettingsSection, label: 'Backup & Restore', icon: <Download size={20} /> },
              { id: 'about' as SettingsSection, label: 'About', icon: <HelpCircle size={20} /> },
              { id: 'advanced' as SettingsSection, label: 'Advanced', icon: <Settings size={20} /> }
            ]).map((item) => (
              <button
                key={item.id}
                onClick={() => setActiveSection(item.id)}
                className={`w-full flex items-center space-x-3 px-4 py-3 rounded-lg text-left ${
                  activeSection === item.id
                    ? 'bg-blue-50 text-blue-700 border border-blue-200'
                    : 'text-gray-700 hover:bg-gray-50'
                }`}
              >
                <div className={`${activeSection === item.id ? 'text-blue-600' : 'text-gray-500'}`}>
                  {item.icon}
                </div>
                <span className="font-medium">{item.label}</span>
              </button>
            ))}
          </nav>
          
          {/* System Info */}
          {systemInfo && (
            <div className="p-4 border-t border-gray-200">
              <h3 className="font-medium text-gray-900 mb-2">System Info</h3>
              <div className="space-y-1 text-sm text-gray-600">
                <div className="flex justify-between">
                  <span>Platform:</span>
                  <span className="font-medium">{systemInfo.platform}</span>
                </div>
                <div className="flex justify-between">
                  <span>Architecture:</span>
                  <span className="font-medium">{systemInfo.arch}</span>
                </div>
                <div className="flex justify-between">
                  <span>App Version:</span>
                  <span className="font-medium">{systemInfo.appVersion}</span>
                </div>
              </div>
            </div>
          )}
        </div>
        
        {/* Settings Content */}
        <div className="lg:col-span-3 overflow-y-auto p-6">
          {/* General Settings */}
          {activeSection === 'general' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">General Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Language */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Globe className="w-5 h-5 mr-2" />
                    Language & Region
                  </h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Interface Language
                      </label>
                      <select
                        value={settings.language}
                        onChange={(e) => handleSettingChange('language', e.target.value)}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        {languageOptions.map((lang) => (
                          <option key={lang.code} value={lang.code}>
                            {lang.flag} {lang.name} ({lang.nativeName})
                          </option>
                        ))}
                      </select>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="animations"
                        checked={settings.animations}
                        onChange={(e) => handleSettingChange('animations', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="animations" className="text-sm text-gray-700">
                        Enable animations
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="tooltips"
                        checked={settings.tooltips}
                        onChange={(e) => handleSettingChange('tooltips', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="tooltips" className="text-sm text-gray-700">
                        Show tooltips
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="notifications"
                        checked={settings.notifications}
                        onChange={(e) => handleSettingChange('notifications', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="notifications" className="text-sm text-gray-700">
                        Enable notifications
                      </label>
                    </div>
                  </div>
                </div>
                
                {/* Startup */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Zap className="w-5 h-5 mr-2" />
                    Startup & Behavior
                  </h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="autoStart"
                        checked={settings.autoStart}
                        onChange={(e) => handleSettingChange('autoStart', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="autoStart" className="text-sm text-gray-700">
                        Start automatically with system
                      </label>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Font Size
                      </label>
                      <div className="flex items-center space-x-4">
                        <input
                          type="range"
                          min="10"
                          max="24"
                          step="1"
                          value={settings.fontSize}
                          onChange={(e) => handleSettingChange('fontSize', parseInt(e.target.value))}
                          className="flex-1"
                        />
                        <span className="text-sm font-medium text-gray-900 w-8">
                          {settings.fontSize}px
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Clipboard Settings */}
          {activeSection === 'clipboard' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Clipboard Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Monitoring */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Monitoring</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Polling Interval (ms)
                      </label>
                      <input
                        type="number"
                        min="100"
                        max="5000"
                        step="100"
                        value={settings.pollInterval}
                        onChange={(e) => handleSettingChange('pollInterval', parseInt(e.target.value))}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                      <p className="text-xs text-gray-500 mt-1">
                        Lower values detect changes faster but use more CPU
                      </p>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Maximum History Items
                      </label>
                      <input
                        type="number"
                        min="10"
                        max="10000"
                        step="10"
                        value={settings.maxHistoryItems}
                        onChange={(e) => handleSettingChange('maxHistoryItems', parseInt(e.target.value))}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                  </div>
                </div>
                
                {/* Capture Settings */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Capture Settings</h3>
                  
                  <div className="space-y-3">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="captureImages"
                        checked={settings.captureImages}
                        onChange={(e) => handleSettingChange('captureImages', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="captureImages" className="text-sm text-gray-700">
                        Capture images
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="captureHtml"
                        checked={settings.captureHtml}
                        onChange={(e) => handleSettingChange('captureHtml', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="captureHtml" className="text-sm text-gray-700">
                        Capture HTML content
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="captureRtf"
                        checked={settings.captureRtf}
                        onChange={(e) => handleSettingChange('captureRtf', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="captureRtf" className="text-sm text-gray-700">
                        Capture RTF content
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="autoClearSensitive"
                        checked={settings.autoClearSensitive}
                        onChange={(e) => handleSettingChange('autoClearSensitive', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="autoClearSensitive" className="text-sm text-gray-700">
                        Automatically clear sensitive data
                      </label>
                    </div>
                    
                    {settings.autoClearSensitive && (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Clear after (minutes)
                        </label>
                        <input
                          type="number"
                          min="1"
                          max="60"
                          value={settings.autoClearMinutes}
                          onChange={(e) => handleSettingChange('autoClearMinutes', parseInt(e.target.value))}
                          className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* AI Settings */}
          {activeSection === 'ai' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">AI Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* AI Configuration */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">AI Configuration</h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="aiEnabled"
                        checked={settings.aiEnabled}
                        onChange={(e) => handleSettingChange('aiEnabled', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="aiEnabled" className="text-sm text-gray-700">
                        Enable AI features
                      </label>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Default AI Model
                      </label>
                      <select
                        value={settings.defaultModel}
                        onChange={(e) => handleSettingChange('defaultModel', e.target.value)}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        {aiModels.map((model) => (
                          <option key={model.id} value={model.id}>
                            {model.name} ({model.size}) {model.local ? '🔴' : '☁️'}
                          </option>
                        ))}
                      </select>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="useCloudModels"
                        checked={settings.useCloudModels}
                        onChange={(e) => handleSettingChange('useCloudModels', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="useCloudModels" className="text-sm text-gray-700">
                        Use cloud AI models (requires API key)
                      </label>
                    </div>
                  </div>
                </div>
                
                {/* Auto-processing */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Auto-processing</h3>
                  
                  <div className="space-y-3">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="autoEnhance"
                        checked={settings.autoEnhance}
                        onChange={(e) => handleSettingChange('autoEnhance', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="autoEnhance" className="text-sm text-gray-700">
                        Auto-enhance new content
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="autoSummarize"
                        checked={settings.autoSummarize}
                        onChange={(e) => handleSettingChange('autoSummarize', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="autoSummarize" className="text-sm text-gray-700">
                        Auto-summarize long content
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="autoClassify"
                        checked={settings.autoClassify}
                        onChange={(e) => handleSettingChange('autoClassify', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="autoClassify" className="text-sm text-gray-700">
                        Auto-classify content type
                      </label>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Confidence Threshold ({Math.round(settings.confidenceThreshold * 100)}%)
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="1"
                        step="0.05"
                        value={settings.confidenceThreshold}
                        onChange={(e) => handleSettingChange('confidenceThreshold', parseFloat(e.target.value))}
                        className="w-full"
                      />
                      <p className="text-xs text-gray-500 mt-1">
                        Higher values require more confidence for AI suggestions
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Appearance Settings */}
          {activeSection === 'appearance' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Appearance Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Theme */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Theme</h3>
                  
                  <div className="grid grid-cols-3 gap-4">
                    {themeOptions.map((theme) => (
                      <button
                        key={theme.id}
                        onClick={() => handleSettingChange('theme', theme.id)}
                        className={`p-4 rounded-lg border-2 flex flex-col items-center space-y-2 ${
                          settings.theme === theme.id
                            ? 'border-blue-500 bg-blue-50'
                            : 'border-gray-200 hover:border-gray-300'
                        }`}
                      >
                        <div className="p-3 rounded-full" style={{ background: theme.colors.background }}>
                          {theme.icon}
                        </div>
                        <span className="text-sm font-medium">{theme.name}</span>
                      </button>
                    ))}
                  </div>
                </div>
                
                {/* UI Preferences */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">UI Preferences</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Sidebar Position
                      </label>
                      <select
                        value={settings.sidebarPosition}
                        onChange={(e) => handleSettingChange('sidebarPosition', e.target.value)}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="left">Left</option>
                        <option value="right">Right</option>
                      </select>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Default View
                      </label>
                      <select
                        value={settings.defaultView}
                        onChange={(e) => handleSettingChange('defaultView', e.target.value)}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="list">List View</option>
                        <option value="grid">Grid View</option>
                        <option value="detailed">Detailed View</option>
                      </select>
                    </div>
                    
                    <div className="space-y-2">
                      <div className="flex items-center space-x-2">
                        <input
                          type="checkbox"
                          id="showLineNumbers"
                          checked={settings.showLineNumbers}
                          onChange={(e) => handleSettingChange('showLineNumbers', e.target.checked)}
                          className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                        />
                        <label htmlFor="showLineNumbers" className="text-sm text-gray-700">
                          Show line numbers
                        </label>
                      </div>
                      
                      <div className="flex items-center space-x-2">
                        <input
                          type="checkbox"
                          id="wordWrap"
                          checked={settings.wordWrap}
                          onChange={(e) => handleSettingChange('wordWrap', e.target.checked)}
                          className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                        />
                        <label htmlFor="wordWrap" className="text-sm text-gray-700">
                          Enable word wrap
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Security Settings */}
          {activeSection === 'security' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Security Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Data Protection */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Shield className="w-5 h-5 mr-2" />
                    Data Protection
                  </h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="encryptSensitive"
                        checked={settings.encryptSensitive}
                        onChange={(e) => handleSettingChange('encryptSensitive', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="encryptSensitive" className="text-sm text-gray-700">
                        Encrypt sensitive data
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="anonymizeData"
                        checked={settings.anonymizeData}
                        onChange={(e) => handleSettingChange('anonymizeData', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="anonymizeData" className="text-sm text-gray-700">
                        Anonymize personal data
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="clearClipboardOnExit"
                        checked={settings.clearClipboardOnExit}
                        onChange={(e) => handleSettingChange('clearClipboardOnExit', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="clearClipboardOnExit" className="text-sm text-gray-700">
                        Clear clipboard on exit
                      </label>
                    </div>
                  </div>
                </div>
                
                {/* Access Control */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Lock className="w-5 h-5 mr-2" />
                    Access Control
                  </h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="requirePassword"
                        checked={settings.requirePassword}
                        onChange={(e) => handleSettingChange('requirePassword', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="requirePassword" className="text-sm text-gray-700">
                        Require password to access
                      </label>
                    </div>
                    
                    {settings.requirePassword && (
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Auto-lock after (minutes)
                        </label>
                        <input
                          type="number"
                          min="1"
                          max="120"
                          value={settings.autoLockMinutes}
                          onChange={(e) => handleSettingChange('autoLockMinutes', parseInt(e.target.value))}
                          className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Performance Settings */}
          {activeSection === 'performance' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Performance Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Cache Settings */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Cache Settings</h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="cacheEnabled"
                        checked={settings.cacheEnabled}
                        onChange={(e) => handleSettingChange('cacheEnabled', e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="cacheEnabled" className="text-sm text-gray-700">
                        Enable caching
                      </label>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Cache Size ({settings.cacheSizeMB} MB)
                      </label>
                      <input
                        type="range"
                        min="10"
                        max="1000"
                        step="10"
                        value={settings.cacheSizeMB}
                        onChange={(e) => handleSettingChange('cacheSizeMB', parseInt(e.target.value))}
                        className="w-full"
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Worker Threads: {settings.workerCount}
                      </label>
                      <input
                        type="range"
                        min="1"
                        max="16"
                        step="1"
                        value={settings.workerCount}
                        onChange={(e) => handleSettingChange('workerCount', parseInt(e.target.value))}
                        className="w-full"
                      />
                      <p className="text-xs text-gray-500 mt-1">
                        More workers improve parallel processing
                      </p>
                    </div>
                  </div>
                </div>
                
                {/* Compression */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Compression</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Compression Level: {settings.compressionLevel}
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="9"
                        step="1"
                        value={settings.compressionLevel}
                        onChange={(e) => handleSettingChange('compressionLevel', parseInt(e.target.value))}
                        className="w-full"
                      />
                      <div className="flex justify-between text-xs text-gray-500 mt-1">
                        <span>Fastest</span>
                        <span>Best Compression</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Storage Settings */}
          {activeSection === 'storage' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Storage Settings</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Storage Type */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Storage Configuration</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Storage Type
                      </label>
                      <div className="space-y-2">
                        {storageTypes.map((type) => (
                          <div
                            key={type.id}
                            className="flex items-center space-x-3 p-3 border rounded-lg hover:bg-gray-50 cursor-pointer"
                            onClick={() => handleSettingChange('storageType', type.id)}
                          >
                            <div className={`w-4 h-4 rounded-full border ${
                              settings.storageType === type.id
                                ? 'border-blue-500 bg-blue-500'
                                : 'border-gray-300'
                            }`} />
                            <div>
                              <div className="font-medium">{type.name}</div>
                              <div className="text-sm text-gray-600">{type.description}</div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
                
                {/* Storage Stats */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Storage Statistics</h3>
                  
                  {stats ? (
                    <div className="space-y-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="bg-gray-50 rounded p-3">
                          <div className="text-sm text-gray-600">Total Items</div>
                          <div className="text-2xl font-semibold text-gray-900">
                            {stats.clipboardHistorySize}
                          </div>
                        </div>
                        <div className="bg-gray-50 rounded p-3">
                          <div className="text-sm text-gray-600">Storage Used</div>
                          <div className="text-2xl font-semibold text-gray-900">
                            {formatFileSize(stats.storageSize)}
                          </div>
                        </div>
                      </div>
                      
                      <div>
                        <div className="text-sm font-medium text-gray-700 mb-2">
                          Items by Type
                        </div>
                        <div className="space-y-2">
                          {Object.entries(stats.itemsByType).map(([type, count]) => (
                            <div key={type} className="flex items-center justify-between">
                              <span className="text-sm text-gray-600">{type}</span>
                              <span className="font-medium">{count}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-8 text-gray-500">
                      Loading statistics...
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
          
          {/* Backup & Restore */}
          {activeSection === 'backup' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Backup & Restore</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Backup */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Download className="w-5 h-5 mr-2" />
                    Backup Data
                  </h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Export Format
                      </label>
                      <select
                        value={exportFormat}
                        onChange={(e) => setExportFormat(e.target.value as 'json' | 'csv')}
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="json">JSON (Full backup)</option>
                        <option value="csv">CSV (Spreadsheet)</option>
                      </select>
                    </div>
                    
                    <div className="space-y-2">
                      <button
                        onClick={exportSettings}
                        className="w-full px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center justify-center"
                      >
                        <Download className="w-4 h-4 mr-2" />
                        Export Settings
                      </button>
                      
                      <button
                        onClick={createBackup}
                        disabled={backupProgress > 0}
                        className="w-full px-4 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 flex items-center justify-center"
                      >
                        <Database className="w-4 h-4 mr-2" />
                        {backupProgress > 0 ? `Creating Backup... ${backupProgress}%` : 'Create Full Backup'}
                      </button>
                      
                      {backupProgress > 0 && backupProgress < 100 && (
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-green-600 h-2 rounded-full transition-all duration-300"
                            style={{ width: `${backupProgress}%` }}
                          />
                        </div>
                      )}
                    </div>
                  </div>
                </div>
                
                {/* Restore */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Upload className="w-5 h-5 mr-2" />
                    Restore Data
                  </h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Import Settings
                      </label>
                      <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                        <Upload className="w-12 h-12 text-gray-400 mx-auto mb-3" />
                        <p className="text-sm text-gray-600 mb-3">
                          Drag & drop settings file or click to browse
                        </p>
                        <input
                          type="file"
                          accept=".json"
                          onChange={(e) => {
                            const file = e.target.files?.[0];
                            if (file) {
                              importSettings(file);
                            }
                          }}
                          className="hidden"
                          id="settings-upload"
                        />
                        <label
                          htmlFor="settings-upload"
                          className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 cursor-pointer"
                        >
                          Browse Files
                        </label>
                        {importFile && (
                          <p className="text-sm text-gray-700 mt-2">
                            Selected: {importFile.name}
                          </p>
                        )}
                      </div>
                    </div>
                    
                    <div className="space-y-2">
                      <button
                        onClick={restoreBackup}
                        disabled={restoreProgress > 0}
                        className="w-full px-4 py-3 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 disabled:opacity-50 flex items-center justify-center"
                      >
                        <RotateCw className="w-4 h-4 mr-2" />
                        {restoreProgress > 0 ? `Restoring... ${restoreProgress}%` : 'Restore from Backup'}
                      </button>
                      
                      {restoreProgress > 0 && restoreProgress < 100 && (
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-yellow-600 h-2 rounded-full transition-all duration-300"
                            style={{ width: `${restoreProgress}%` }}
                          />
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Data Management */}
              <div className="bg-white rounded-lg border border-gray-200 p-6">
                <h3 className="font-medium text-gray-900 mb-4">Data Management</h3>
                
                <div className="space-y-4">
                  <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                    <div className="flex items-start">
                      <AlertTriangle className="w-5 h-5 text-red-500 mt-0.5 mr-3" />
                      <div>
                        <h4 className="font-medium text-red-800">Danger Zone</h4>
                        <p className="text-sm text-red-700 mt-1">
                          These actions are irreversible. Please proceed with caution.
                        </p>
                      </div>
                    </div>
                    
                    <div className="mt-4 space-y-3">
                      <button
                        onClick={clearAllData}
                        className="w-full px-4 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center justify-center"
                      >
                        <Trash2 className="w-4 h-4 mr-2" />
                        Clear All Clipboard Data
                      </button>
                      
                      <p className="text-xs text-red-600">
                        This will permanently delete all clipboard history, favorites, and settings.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* About */}
          {activeSection === 'about' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">About Knoux Clipboard AI</h2>
              
              <div className="bg-white rounded-lg border border-gray-200 p-6">
                <div className="flex items-center space-x-4 mb-6">
                  <div className="p-4 bg-gradient-to-r from-blue-500 to-purple-500 rounded-xl">
                    <Settings className="w-8 h-8 text-white" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-gray-900">Knoux Clipboard AI</h3>
                    <p className="text-gray-600">Version 1.0.0</p>
                  </div>
                </div>
                
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Description</h4>
                    <p className="text-gray-600">
                      Knoux Clipboard AI is an intelligent clipboard manager that uses artificial intelligence
                      to analyze, enhance, and organize your clipboard contents. It provides powerful features
                      for developers, writers, and professionals who work with text and code.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">Features</h4>
                    <ul className="list-disc list-inside text-gray-600 space-y-1">
                      <li>AI-powered content analysis and enhancement</li>
                      <li>Intelligent clipboard history with search</li>
                      <li>Code analysis and improvement suggestions</li>
                      <li>Sensitive data detection and protection</li>
                      <li>Cross-platform compatibility</li>
                      <li>Customizable themes and settings</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-medium text-gray-900 mb-2">System Requirements</h4>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="bg-gray-50 rounded p-3">
                        <div className="text-sm text-gray-600">Operating System</div>
                        <div className="font-medium">Windows 10+, macOS 10.14+, Linux</div>
                      </div>
                      <div className="bg-gray-50 rounded p-3">
                        <div className="text-sm text-gray-600">Memory</div>
                        <div className="font-medium">4GB RAM minimum</div>
                      </div>
                      <div className="bg-gray-50 rounded p-3">
                        <div className="text-sm text-gray-600">Storage</div>
                        <div className="font-medium">200MB free space</div>
                      </div>
                      <div className="bg-gray-50 rounded p-3">
                        <div className="text-sm text-gray-600">AI Models</div>
                        <div className="font-medium">2GB+ for local models</div>
                      </div>
                    </div>
                  </div>
                  
                  <div className="pt-4 border-t border-gray-200">
                    <h4 className="font-medium text-gray-900 mb-2">Support & Resources</h4>
                    <div className="flex space-x-3">
                      <button className="px-4 py-2 bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200">
                        Documentation
                      </button>
                      <button className="px-4 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200">
                        Report Issue
                      </button>
                      <button className="px-4 py-2 bg-green-100 text-green-700 rounded-lg hover:bg-green-200">
                        Check for Updates
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Advanced Settings */}
          {activeSection === 'advanced' && (
            <div className="space-y-6">
              <h2 className="text-xl font-bold text-gray-900">Advanced Settings</h2>
              
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
                <div className="flex items-start">
                  <AlertTriangle className="w-5 h-5 text-yellow-600 mt-0.5 mr-3" />
                  <div>
                    <h4 className="font-medium text-yellow-800">Warning</h4>
                    <p className="text-sm text-yellow-700 mt-1">
                      These settings are for advanced users. Changing them may affect application
                      stability and performance.
                    </p>
                  </div>
                </div>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Debug Settings */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4">Debug Settings</h3>
                  
                  <div className="space-y-4">
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="debugMode"
                        checked={showAdvancedOptions}
                        onChange={(e) => setShowAdvancedOptions(e.target.checked)}
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="debugMode" className="text-sm text-gray-700">
                        Enable debug mode
                      </label>
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="verboseLogging"
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="verboseLogging" className="text-sm text-gray-700">
                        Enable verbose logging
                      </label>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Log Level
                      </label>
                      <select className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500">
                        <option value="error">Error</option>
                        <option value="warn">Warning</option>
                        <option value="info">Info</option>
                        <option value="debug">Debug</option>
                        <option value="verbose">Verbose</option>
                      </select>
                    </div>
                    
                    <button className="w-full px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50">
                      Export Debug Logs
                    </button>
                  </div>
                </div>
                
                {/* Network Settings */}
                <div className="bg-white rounded-lg border border-gray-200 p-6">
                  <h3 className="font-medium text-gray-900 mb-4 flex items-center">
                    <Network className="w-5 h-5 mr-2" />
                    Network Settings
                  </h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        API Timeout (seconds)
                      </label>
                      <input
                        type="number"
                        min="5"
                        max="120"
                        defaultValue="30"
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Max Concurrent Requests
                      </label>
                      <input
                        type="number"
                        min="1"
                        max="20"
                        defaultValue="5"
                        className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                    
                    <div className="flex items-center space-x-2">
                      <input
                        type="checkbox"
                        id="useProxy"
                        className="h-4 w-4 text-blue-600 rounded focus:ring-blue-500"
                      />
                      <label htmlFor="useProxy" className="text-sm text-gray-700">
                        Use proxy server
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* Reset Section */}
              <div className="bg-white rounded-lg border border-gray-200 p-6">
                <h3 className="font-medium text-gray-900 mb-4">Reset & Reinstall</h3>
                
                <div className="space-y-3">
                  <button
                    onClick={() => setShowResetConfirm(true)}
                    className="w-full px-4 py-3 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 flex items-center justify-center"
                  >
                    <RotateCw className="w-4 h-4 mr-2" />
                    Reset All Settings to Default
                  </button>
                  
                  <button className="w-full px-4 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center justify-center">
                    <Trash2 className="w-4 h-4 mr-2" />
                    Uninstall Application
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
      
      {/* Reset Confirmation Modal */}
      {showResetConfirm && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center space-x-3 mb-4">
              <div className="p-2 bg-yellow-100 rounded-full">
                <AlertTriangle className="w-6 h-6 text-yellow-600" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-gray-900">Reset Settings</h3>
                <p className="text-gray-600">Are you sure you want to reset all settings to default?</p>
              </div>
            </div>
            
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
              <p className="text-sm text-yellow-700">
                This action will reset all your preferences, including AI settings, security
                options, and UI customizations. This cannot be undone.
              </p>
            </div>
            
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => setShowResetConfirm(false)}
                className="px-4 py-2 text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={resetToDefaults}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"
              >
                Reset All Settings
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

